### ISSUE TITLE
Is it stable and would you like to create a demo?

### ISSUE THREAD

**Issue by sqc1999** [blogifierdotnet/blogifier#1]
Hello, @rxtur! I didn't notice this project until yesterday. And I think it is why the BlogEngine.NET project almost stopped to update in the last a few weeks.
I am so happy that here is such a project because I started to learn .NET Core and ASP.NET Core just now.
For some reason I can't install .NET Core on the computer I am currently using, so I can't try it out now. Could you please tell me is the project stable now and would you like to create a demo for it like zoo.azurewebsites.net(which is for BlogEngine.NET)?
I know this is not an issue at all, but I could not find any other ways to contact you XD.

**Comment by rxtur** [comment]
Well, it is not yet stable and needs lot of work, but there is a "demo" at http://blogifier.azurewebsites.net

You can log in with account below:
doug@us.com / Blogifier@1
