### ISSUE TITLE
Changing the code languages with custom Prism download

### ISSUE THREAD

**Issue by kylepmanuel** [blogifierdotnet/Blogifier#1]
How do you add/change code languages in the editor and use a custom prism download?
I tried replacing the existing Prism file with a custom one.  I also tried adding codesample_languages to the tinymce init.

**Comment by francisdotbio** [comment]
For adding your code to the editor:

![01](https://user-images.githubusercontent.com/6384978/32407087-c7b987cc-c198-11e7-830d-cfd4c9f66363.png)

Here are some of the default languages that you can select:

![02](https://user-images.githubusercontent.com/6384978/32407089-c9846720-c198-11e7-973f-0987f4d91b21.png)

-----

For adding language to that list, you have to add them in the `editorController.js` file.
here is an example:
```
tinymce.init({
  selector: 'textarea',
  plugins: 'codesample',
  codesample_languages: [
        {text: 'HTML/XML', value: 'markup'},
        {text: 'JavaScript', value: 'javascript'},
        {text: 'CSS', value: 'css'},
        {text: 'PHP', value: 'php'},
        {text: 'Ruby', value: 'ruby'},
        {text: 'Python', value: 'python'},
        {text: 'Java', value: 'java'},
        {text: 'C', value: 'c'},
        {text: 'C#', value: 'csharp'},
        {text: 'C++', value: 'cpp'}
    ],
  toolbar: 'codesample'
});
```
which we already added in the plugins and toolbar, so you need to add only `codesample_languages`.

Read more about this on the TinyMCE website:
https://www.tinymce.com/docs/plugins/codesample/

**Comment by kylepmanuel** [comment]
I had tried that before.  I was trying to add at least SQL to the list.  I would like to get SASS, PowerShell, and GraphQL in there too.

`
 tinymce.init({
        skin: "blogifier",
        selector: '#txtContent',
        plugins: [
            "autoresize autolink lists link image code textcolor imagetools hr media table contextmenu fileupload codesample placeholder"
        ],
        codesample_languages: [
            { text: 'HTML/XML', value: 'markup' },
            { text: 'JavaScript', value: 'javascript' },
            { text: 'CSS', value: 'css' },
            { text: 'SQL', value: 'sql' },
            { text: 'Ruby', value: 'ruby' },
            { text: 'Python', value: 'python' },
            { text: 'Java', value: 'java' },
            { text: 'C', value: 'c' },
            { text: 'C#', value: 'csharp' },
            { text: 'C++', value: 'cpp' }
        ],
`

**Comment by francisdotbio** [comment]
Since I was working on Editor last night and today. I've added Sass (SCSS) and SQL, so now you can use them.
But, It's on `dev` branch now!

Remember you have to have the prism JS and CSS on your theme. by default, we have it on the "OneThree" theme.
