### ISSUE TITLE
conditional statement of Disqus not working

### ISSUE THREAD

**Issue by farzindev** [blogifierdotnet/Blogifier#10]
In the "single.schtml" Conditional statement of Disqus is not working.
There are some CSS styles applied to the HTML wrapper of the Disqus that we don't want to be there when Disqus is not there.

**Comment by rxtur** [comment]
Not sure I understand this issue - don't see anything in HTML when disqus not enabled.

**Comment by rxtur** [comment]
Ok, so it happens when you save empty string as disqus script. Fixed.
