### ISSUE TITLE
Migration from previous version

### ISSUE THREAD

**Issue by curia-damiano** [blogifierdotnet/Blogifier#106]
Hi,
I have a blog in production running on Sqlite.
Is there a way to easily migrate from the version running on Asp.Net Core 2?
Regards, Damiano

**Comment by curia-damiano** [comment]
Hi rxtur,
thank you for your help! I thought at this option, I didn't know if there would have been a more direct way.

Now: on my machine, I've downloaded the updated version. I log in as Admin and I create a new user (as admin btw) from the Admin portal.
Then I try to log in with my user (to then import from the rss.xml) but I can't.

I've checked the Sqlite db, and I see that the user is created in the Authors table, but not in AspNetUsers.

Should I create it by hand there, or it is not important? Because as said, I can't log in...

Regards, Damiano

**Comment by rxtur** [comment]
I'm guessing something went wrong in your test, I just tried it with latest (2.0.0.9) and was able to create new admin, delete old admin and demo accounts and new admin is the only one in AspNetUsers as expected. 
Sqlite sometimes tricky when moving it around, it locks and caches data, so you might need to restart app, clear browser cache etc. I didn't have to do any of this though, it just worked for a site pushed from source to local IIS.

**Comment by curia-damiano** [comment]
Hey rxtur,
I have tried again.
Creating a login "Damiano" everything works fine, while with the login "Damiano Curia" I get the same behavior.

**Comment by UnlawfulCitizen** [comment]
I was able to recreate the login behavior.

It has to do with the user having a space in the username.  Which is piggybacking off the asp.net core  identity system.
