### ISSUE TITLE
wwwroot added to uploaded image file paths in Azure

### ISSUE THREAD

**Issue by asherrick02** [blogifierdotnet/Blogifier#107]
Everything works fine locally in IIS Express, but when I deploy to Azure "wwwroot" is being added to the beginning of uploaded image file paths. Anything already in the DB displays properly.

My Azure site is configured with a virtual directory of "/" pointing to a physical path of "site\wwwroot" and set to an application (not directory).

**Comment by rxtur** [comment]
Yes, just noticed it in demo site too, will take care of it tomorrow.

**Comment by rxtur** [comment]
This has been fixed.

**Comment by asherrick02** [comment]
Wow, that was fast! Thank you.
