### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by asherrick02** [blogifierdotnet/Blogifier#109]
Will post tagging be added in the near future? This is probably the only must-have feature that's missing, in my opinion. Custom pages and a contact form would be great, too, but those are easy enough to add manually as-needed.

**Comment by rxtur** [comment]
You can add "categories" to the post (upper right "settings" button in the post edit). This is comma delimited, so you can add multiple.

Categories and tags are mostly interchangeable, RSS only supports categories anyways, so it goes down to something like:
````
 <pubDate>Sat, 3 Jun 2017 13:35:00 -0700</pubDate>
 <category>asp.net</category>
 <category>blogging</category>
 <dc:publisher>rtur.net</dc:publisher>
````

**Comment by asherrick02** [comment]
I typically use tags in a much more granular way than categories. 

For example, if I had a blog about ASP.NET development my categories would be broader topics like tutorials, performance, security, etc whereas my tags might be very specific technologies (or even classes) like Razor, IConfiguration, DI, etc. In this scenario I could write a post about how to setup Blogifier that I would categorize as a "Tutorial" and in the post I might discuss specifics technologies and tag it with Razor, IConfiguration, and DI.

**Comment by rxtur** [comment]
This is something that likely will be added as menu widget, once I'm done with core functionality and move on plugins and widgets.
