### ISSUE TITLE
MetaWebLog support

### ISSUE THREAD

**Issue by asherrick02** [blogifierdotnet/Blogifier#110]
Does Blogifier support MetaWebLog? If not, is there any plan to?

**Comment by rxtur** [comment]
No and there is no immediate plans. Given built-in editor works great I just don't think support for external clients is high priority.

**Comment by asherrick02** [comment]
Funny you should mention the editor (Markdown)...that's actually why I was looking at MetaWebLog. Some users prefer an RTE.

**Comment by rxtur** [comment]
Understand, but trying to make it work for everyone everywhere is a dead end, learned it hard way.
