### ISSUE TITLE
Init Run and Setup - Cannot insert null into Authors table

### ISSUE THREAD

**Issue by flashvenom** [blogifierdotnet/Blogifier#114]
Fairly to dotNetCore, but worked a ton with MVC in the past, so please excuse my ignorance. I figure this issue might help helpful to other beginners using this project with SQL Server who might fall into my situation as well...

So far I've:
-Cloned the project and opened in Visual Studio 2017 15.8.5
-Ran "Script-Migration -from 0 -c AppDbContext" to generate SQL scripts and created the tables in my db server
-Changed appsettings.json DbProvider to "SqlServer"
-Changed appsettings.json ConnString to "Server=tcp:sql.myserver.com,1433;Data Source=sql.myserver.com;Initial Catalog=mydatabase;Persist Security Info=False;User ID=username;Password=password;MultipleActiveResultSets=True;"
-Changed appsettings.json DemoMode to false
-Changed line 37 of Startup.cs to include "options.UseSqlServer"

I am now getting an error:
"SqlException: Cannot insert the value NULL into column 'Id', table 'mydatabase.dbo.Authors'; column does not allow nulls. UPDATE fails."

Am I missing something?

**Comment by rxtur** [comment]
If you look under Core/Migrations in the VS solution, there generated code that is specific to SQLite. You'll see things like:
```
.Annotation("Sqlite:Autoincrement", true)
```
I believe you need to add SQL Server annotation here:
```
.Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
```
When I test for SQL Server, I just wipe out migrations and re-generate them for SQL Server. But adding annotations manually should work too. I'll probably add them to make it work for both out of the box.

**Comment by rxtur** [comment]
The latest commit should work with SQL Server out of the box. You just change connection string/provider and run application, it should created database and seed it with data.
