### ISSUE TITLE
User.Identity.IsAuthenticated always false after PasswordSignInAsync gives success

### ISSUE THREAD

**Issue by pttien** [blogifierdotnet/Blogifier#115]
Can not access Admin page after login because User.Identity.IsAuthenticated always false after PasswordSignInAsync gives success

**Comment by rxtur** [comment]
Is this something related to language/culture settings you use? Can you give me a test case - what exactly you doing? Do built-in accounts (demo and admin) work for you?

**Comment by rxtur** [comment]
I think I actually figured out what you meant and made it work with other cultures like Chinese etc.
