### ISSUE TITLE
User Account Demo

### ISSUE THREAD

**Issue by junnavarra** [blogifierdotnet/Blogifier#116]
New user created cannot login. It seems like it sticks to the user account demo. Do we have workaround on this in code. Thanks.

**Comment by rxtur** [comment]
Can't re-create this. If you go to sample site (blogifier.azurewebsites.net) and create new user there - are you able to log in?

**Comment by junnavarra** [comment]
Downloading latest copy from GitHub resolves the issue. I'm still testing it on localhost but I plan to deploy it on my existing ASP.NET hosting provider not on Azure. Thanks for the update.

**Comment by junnavarra** [comment]
Just an observation in the database, user account credentials are stored in AspNetUsers and Authors, I can't see foreign key relationships between the two tables. 

Thanks.

**Comment by rxtur** [comment]
This more like two databases running side-by-side, foreign key can be added but not necessary for our usage.
