### ISSUE TITLE
Not login

### ISSUE THREAD

**Issue by green16** [blogifierdotnet/Blogifier#117]
**log**

> info: Microsoft.AspNetCore.Server.Kestrel[17]
>       Connection id "0HLHUAGU3OQG0" bad request data: "Requests with 'Connection: Upgrade' cannot have content in the request body."
> Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Requests with 'Connection: Upgrade' cannot have content in the request body.
>    at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.For(HttpVersion httpVersion, HttpRequestHeaders headers, Http1Connection context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.CreateMessageBody()
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)

**Comment by rxtur** [comment]
Does it work for simple Latin characters (demo/demo etc)?
If it works for simple cases, what name/password is not working?

**Comment by green16** [comment]
I tried the demo/demo and admin/admin

**Comment by green16** [comment]
hmm It looks like the problem is not with you. On x86(My pc) everything works, but there is no arm(Orange pi zero).

**Comment by rxtur** [comment]
Ok, that's probably a little over my head :)
