### ISSUE TITLE
Can't load my created ClassLibrary in the Controller.

### ISSUE THREAD

**Issue by tanshanli** [blogifierdotnet/Blogifier#123]
## Current behavior
Can't load my created ClassLibrary(TargetFramework netcoreapp2.1) in the AdminController.
but,The program is not interrupted.
 ![error.png](http://oss.z13qu.com/issue/blogifierdotnet/Blogifier/error.png)

However. Variables(my created ClassLibrary) in App/Program.cs or App/Startup.cs   can be displayed normally.
![normal.png](http://oss.z13qu.com/issue/blogifierdotnet/Blogifier/normal.png)

## Expected behavior
Variables(my created ClassLibrary) in the AdminController can be displayed normally.

## Try
When I created a new project(net core 2.1 mvc),Reference to the same ClassLibrary,Everything's fine.

## Environment
Version: Blogifier\App 1.0.0,
TargetFramework: netcoreapp2.1
Tool: VS2017 15.9.4
OS Version and name:  win10 1803

**Comment by rxtur** [comment]
If you look at [Plugins.Common](https://github.com/blogifierdotnet/Blogifier/blob/master/plugins/Common/Common.csproj) project, it is external class library that references Core. It includes views, controllers and classes that interact with Blogifier. The only thing that required for Blogifier to instantiate and run this library is set product attribute to start with `Blogifier.`. At startup, Blogifier will check all DLLs in the `~/bin` for this attribute and load library as plugin. This way you don't have to mess with core application code and rebuild it on every upgrade.

**Comment by tanshanli** [comment]
thx

**Comment by tanshanli** [comment]
> If you look at [Plugins.Common](https://github.com/blogifierdotnet/Blogifier/blob/master/plugins/Common/Common.csproj) project, it is external class library that references Core. It includes views, controllers and classes that interact with Blogifier. The only thing that required for Blogifier to instantiate and run this library is set product attribute to start with `Blogifier.`. At startup, Blogifier will check all DLLs in the `~/bin` for this attribute and load library as plugin. This way you don't have to mess with core application code and rebuild it on every upgrade.

thx
