### ISSUE TITLE
How can deploy blogifier to server with SQL Server

### ISSUE THREAD

**Issue by emreordukaya** [blogifierdotnet/Blogifier#133]
Hi I want to use blogifier on windows server with sql server. I want to setup it start to end. So I havent ant blogengine. I wont upgrade. I will setup blogifier on clean server. what can I do for setup.

**Comment by rxtur** [comment]
Create new database on your server and [modify appsettings.json to use SQL Server provider and connection string](https://github.com/blogifierdotnet/Blogifier/blob/master/docs/SqlServer.md).

Once you deploy application to the server and navigate to it in the browser, Blogifier will create DB tables and, if you choose so in the same configuration file, seed it with sample data.

**Comment by emreordukaya** [comment]
> Create new database on your server and modify appsettings.json to use SQL Server provider and connection string.
> Once you deploy application to the server and navigate to it in the browser, Blogifier will create DB tables and, if you choose so in the same configuration file, seed it with sample data.

Ok but I don't know which files that I have to upload to my server.

1-) Total folder -- https://github.com/blogifierdotnet/Blogifier ?
2-) The files in this folder -- https://github.com/blogifierdotnet/Blogifier/tree/master/src/App ?
3-) Or this core folder -- https://github.com/blogifierdotnet/Blogifier/tree/master/src/Core ?

So How can I upload files and then I will create a database on MS SQL server. then I will change appsettings.json to use SQL Server provider and connection string. After all then I will browse. but which files will I upload to server.
Also I looked this files via VS -- https://github.com/blogifierdotnet/Blogifier.Net -- This Project site doesn't contain any admin controller. Then I wonder which files will upload to server. 
Can u help me how can I do this.

**Comment by rxtur** [comment]
You can pull compiled and ready to publish from latest release:

[https://github.com/blogifierdotnet/Blogifier/releases/download/v2.3/Blogifier.2.3.zip](https://github.com/blogifierdotnet/Blogifier/releases/download/v2.3/Blogifier.2.3.zip)

**Comment by emreordukaya** [comment]
> You can pull compiled and ready to publish from latest release:
> https://github.com/blogifierdotnet/Blogifier/releases/download/v2.3/Blogifier.2.3.zip

Ok I find it. All files compiled. but I want to upload uncompiled files. So I can add file or add control to code. which part of this code can I upload.

1-) Total folder -- https://github.com/blogifierdotnet/Blogifier ?
2-) The files in this folder -- https://github.com/blogifierdotnet/Blogifier/tree/master/src/App ?
3-) Or this core folder -- https://github.com/blogifierdotnet/Blogifier/tree/master/src/Core ?

**Comment by rxtur** [comment]
1.
