### ISSUE TITLE
Deploy Blogifier to CentOS7

### ISSUE THREAD

**Issue by vanpard** [blogifierdotnet/Blogifier#135]
I’ve followed the instruction of `Build.md` and used powershell to build locally, and it turned out to be successful while entering the command “dotnet App.dll”.
**But when I deployed it onto CentOS by uploading the whole `build/publish` folder, it showed:**
```
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/roo
t/publish/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /root/publish/App.runtimeconfig.json file specifying the appropriate framework.
```
After I uploading all of the required `*.json` files, it showed 
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString.
```
**So, how to deploy this app to centos7?**
Besides, I've tried to run `dotnet publish -c Release` and `dotnet App.dll`, it also failed with the msg:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLKLE3ID7DCR", Request id "0HLKLE3ID7DCR:00000001": An unhandled exception was thrown by the application.
```
Thanks.

**Comment by rxtur** [comment]
I have walk-through on publishing to Ubuntu [here](http://rtur.net/posts/asp.net-core-on-digitalocean-jumpstart) you may check with, unless CentOS has something specific in requirements.

**Comment by vanpard** [comment]
It reminds me that I have to upload the `refs`and `runtime` folder, and finally the app works on CentOS7!
thanks.
