### ISSUE TITLE
IViewLocalizer Localizer - JSON Array Error on List, Post.cshtml

### ISSUE THREAD

**Issue by neo302** [blogifierdotnet/Blogifier#138]
Why does adding?
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
to the List, Post, or any of the views within the themes cause the JSON error below?  I'm also curious as to why if I visit the admin page, then go back to the List or Post view, the error goes away?  What happens or loads when visiting the admin pages that allows IViewLocalizer to work on the List/Post views after visiting the admin page?

Thank you!

An unhandled exception occurred while processing the request.
JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Askmethat.Aspnet.JsonLocalizer.Format.JsonLocalizationFormat]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.

**Comment by rxtur** [comment]
Fixed with 2.3.1 update, standard theme has example usage in the List.cshtml
