### ISSUE TITLE
Deploy as Sub Site

### ISSUE THREAD

**Issue by robertmadsen** [blogifierdotnet/Blogifier#141]
I want to deploy Blogifier as a subsite (that is, in a folder) of an existing website. This way I can access the blog by http://existingsite.com/blog/

The existing site is hosted as an Azure app.

I have successfully downloaded and built the standalone Blogifier code. What must I do to do the same except as a sub-site as described above?

**Comment by rxtur** [comment]
This is not really supported. Taking dependency on another application opens up can of worms, with number of scenarios to support going up exponentially. The "parent" application can be very different and what works for one does not work for others.

**Comment by alexkusuma** [comment]
@robertmadsen  Can you convert the sub folder into application? If you can, you then assign it to a new worker running .netcore. You then deploy the compiled code into the sub folder. That way IIS will treat them as separate applications, but visitors can access them as you planned: existingsite.com/blog/ for blogifier and existingsite.com for the existing engine. I deployed something like that a month ago on my iis web server and it works well; i didn’t host them as azure apps, though.

**Comment by robertmadsen** [comment]
Thanks. I will give this a try.

**Comment by fordprefect480** [comment]
@robertmadsen I have almost the exact same setup and want to do the same thing. Please report back if you get it working.

**Comment by robertmadsen** [comment]
Here is were I am at. Our site is http://synaptixgames,com. I created a subfolder called _blog_. I went into Azure portal for the site at **Configuration/Path mappings** and added _blog_ as a _Virtual application or directory_ at the _Physical Path_ **site\wwwroot\blog**, then published the blog to _http://www.synaptixgames.com/blog_.

Some of the files end up correctly at http://synaptixgames.com/blog, but all of the dynamic content, such as the data and posts, still get generated at the root http://synaptixgames.com.

I figure there is something I'm missing...some setting that indicates that the blog application should treat http://synaptixgames.com/blog as the root of that application.

Anyone  have any ideas? @alexkusuma I was trying to implement your idea but couldn't quite figure it out. For example, VS won't allow me to precompile the blog app when I publish it. Usually this option comes up in the publish dialog.

**Comment by alexkusuma** [comment]
Hi Robert,

Have you check the routing table/route settings ?
What happen if you add /blog as prefix for all of the routes?
I hope this helps.

Cheers,
Alex

**Comment by rxtur** [comment]
Closing old comments to avoid confusion, lots changed.
