### ISSUE TITLE
Issue Updating Image/Avatar

### ISSUE THREAD

**Issue by XxDaShTixX** [blogifierdotnet/Blogifier#142]
Hello,

Deploying the app to IIS works just fine. But when I try to update my avatar the image icons on the site don't show up as if the url is broken. This tells me that the app is unable to retrieve the images. 
![Untitled](https://user-images.githubusercontent.com/11358087/56332721-76892e80-615f-11e9-8aaf-7952e37959e1.png)

Also, when I try to delete an existing image (or one that I uploaded) I get at the lower right corner of the screen "Error 500" in red. 
![asda](https://user-images.githubusercontent.com/11358087/56332859-f1524980-615f-11e9-8572-01f8a54374e4.png)

Other images (cover, banner etc) show up just fine on the site itself, I only get this issue when trying to update images/avatars. The image uploads fine, but when I select a new image, it just doesn't show. Just shows as broken
![adsasd](https://user-images.githubusercontent.com/11358087/56332920-278fc900-6160-11e9-9030-a07133e08213.png)

I double checked that the IIS has the right permissions but it was no use. When I am testing locally, I am able to do everything just fine, but when I deploy the app on my server this happens. Note that I have another ASP.NET core application hosted on the same server that is working fine.

Any help or suggestions is appreciated.

Thank you very much in advance.

**Comment by rxtur** [comment]
I don't see this issue when deploy to local IIS, probably something to do with permissions or IIS settings/configuration.

Most likely something like [this](https://stackoverflow.com/questions/12440277/how-do-i-enable-http-put-and-delete-for-asp-net-mvc-in-iis).

**Comment by VhThomas** [comment]
I am facing exactly the same issue and updating the web.Config did not resolve my problem. 
But what I can tell is that somehow (IIS hosted on server), it appends nameofwebsite/wwwroot in front of data/admin/year/month/imgname.jpg.

When removing manually nameofwebsite/wwwroot then it shows up the image... So the following shows first image ok, second not ok and third ok.

![image](https://user-images.githubusercontent.com/16691980/59070444-083d2e80-88bb-11e9-8a08-91f95b1aee88.png)

Result when viewing the post is the following:

![image](https://user-images.githubusercontent.com/16691980/59070496-36227300-88bb-11e9-9a79-55550c101fef.png)
