### ISSUE TITLE
How to tell what version you are on?

### ISSUE THREAD

**Issue by flashvenom** [blogifierdotnet/Blogifier#144]
Maybe I'm missing it, but where in the source files can you tell what 'version' of the code you're running. It would be helpful to put the Blogifier version somewhere on the admin UI (especially with the new upgrade capabilities.)

**Comment by rxtur** [comment]
Added "about" page with version number.

![about](https://user-images.githubusercontent.com/1932785/56703130-249b5800-66cd-11e9-8465-e25e0bfb0b0e.PNG)
