### ISSUE TITLE
Can't access images

### ISSUE THREAD

**Issue by robertmadsen** [blogifierdotnet/Blogifier#147]
I can upload images, but when I select them I always get an Requested Resource Not Found.

![gallery](https://user-images.githubusercontent.com/1307315/57398580-9626dc00-718c-11e9-8b2a-a1fad26e3747.png)

![error404](https://user-images.githubusercontent.com/1307315/57398590-9f17ad80-718c-11e9-806a-5da96aa6d88d.png)

**Comment by rxtur** [comment]
Did you modify your install in some way or you getting this on plain standard setup?

**Comment by robertmadsen** [comment]
I used VS 2017 to publish the app folder. I right clicked on the app folder in Solution Explorer and used Publish.

**Comment by rxtur** [comment]
I just added [troubleshooting section](https://github.com/blogifierdotnet/Blogifier/blob/master/docs/Troubleshooting.md) to wiki, point is I need to reproduce this error to fix it and it sure works fine for me so I need to understand what you do differently.

**Comment by robertmadsen** [comment]
Thanks so much. I will take a look at this tomorrow and give you feedback. I also noticed a similar issue reported in the closed issues, but that dealt with IIS permission and I don't know if it is relevant. I am hosting my site as a web app on Azure.
