### ISSUE TITLE
Missing: Avatar linked to User

### ISSUE THREAD

**Issue by robertmadsen** [blogifierdotnet/Blogifier#148]
Right now it appears there are two avatars: one for the admin and one for all users,. It would be nice if I can create an avatar for each user.

Thx for the great product.

**Comment by rxtur** [comment]
User can upload any image and set it as avatar in the admin/settings/profile.

**Comment by robertmadsen** [comment]
Thx. I have another issue the I posted. The functionality to assign images isn't working.
