### ISSUE TITLE
Asset Storage

### ISSUE THREAD

**Issue by murst** [blogifierdotnet/Blogifier#15]
Asset storage should be more flexible. Right now, it assumes all files (such as themes, profile logos, post images, etc) are stored in the same location (because they all use the same Blogifier.Core.Services.FileSystem.BlogStorage class). For hosts like Azure it might be fine to assume that themes are in the application directory, but post images would probably be better in a blob.

We should be able to configure which IBlobStorage providers are used for assets and themes.

I'm guessing it would probably be most appropriate to create an AzureBlob storage provider that implements IBlobStorage in the WebApp, and pass it into Blogifier, so that Blogifier.Core wouldn't have any dependencies on Azure.

This might already be on your to-do list, but I thought I'd create an issue in case it is not.

**Comment by rxtur** [comment]
There will be asset provider, so you can add Dropbox, OneDrive etc. Along with search, filters and so on.  Ideally, I want to shoot picture and have it in the file picker as soon as it uploaded to the cloud. We just not there yet.

**Comment by murst** [comment]
Great, I figured that was going to be the case since there was an IBlogStorage interface. I didn't think about OneDrive/DropBox integration. That sounds pretty interesting.
