### ISSUE TITLE
Provide a richer makedown format

### ISSUE THREAD

**Issue by GitHub-Pan** [blogifierdotnet/Blogifier#152]
Hello, first of all this is a feature suggestion. I met a problem. When I am writing a blog, I sometimes need to draw a simple table. However, Blogifier does not support the makedown format of the form. In order to achieve the effect I need, I can only draw the form in word and embed it as a picture. So I hope to provide more support for the makedown format, or provide some help.

by the way ,English is not my native language, I don't know if you can understand what I mean.
I hope to get your help or provide some suggestions.thanks very much !

**Comment by rxtur** [comment]
Please keep in mind you can always use HTML if markdown falls short, mixing both in the same post content.

**Comment by GitHub-Pan** [comment]
Thank you for your reply, using  HTML is indeed a good solution.
