### ISSUE TITLE
Demo site 500

### ISSUE THREAD

**Issue by LucaGabi** [blogifierdotnet/Blogifier#153]
Hi,

The demo site returns 500 on login atempt.

**Comment by NinjaCodeVixen** [comment]
i see the same thing. interestingly enough, my version of the same in azure is throwing a 500 as well.  so running locally in debug, and i believe it has to do with changing to the "simple" template, then attempting to log on.  "returnUrl" is null at this point.

NullReferenceException: Object reference not set to an instance of an object.
Core.StringExtensions.SanitizePath(string str) in StringExtensions.cs
+
            str = str.Replace("%2E", ".").Replace("%2F", "/");
App.Pages.Account.LoginModel.RedirectToLocal(string returnUrl) in Login.cshtml.cs
+
            returnUrl = returnUrl.SanitizePath();
App.Pages.Account.LoginModel.OnPostAsync(string returnUrl) in Login.cshtml.cs
+
                    return RedirectToLocal(returnUrl);
Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory+GenericTaskHandlerMethod.Convert<T>(object taskAsObject)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory+GenericTaskHandlerMethod.Execute(object receiver, object[] arguments)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeHandlerMethodAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeNextPageFilterAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by rxtur** [comment]
When demo site on Azure goes down, you can try http://blogifier.net/blog instead.

**Comment by rxtur** [comment]
Switched to use blogifier.net/blog
