### ISSUE TITLE
Empty post cover won't show default blog cover

### ISSUE THREAD

**Issue by mosakashaka** [blogifierdotnet/Blogifier#154]
I'm using vision theme, when a post's cover is an empty string, no default cover is shown for that post in the list view.

Code in List.cshtml is:
```c#

var img = string.IsNullOrEmpty(item.Cover) ? Model.Blog.Cover : item.Cover;
<article class="post">
	<div class="post-cover">

		<ul class="post-categories">
			<li><a href="#">Technology</a></li>
			<li><a href="#">Microsoft</a></li>
		</ul>

		<a href="~/posts/@item.Slug">
			<img src="~/@img" alt="@item.Title">
		</a>
		@if (item.Featured)
				{
		<span class="post-featrued-label"><i class="fa fa-star"></i> Featured</span>
				}
	</div>
```

Because `Model.Blog.Cover` already has a `/` (slash) at the beginning, the populated post cover will be have `~//` at the beginning, and image will not be located.

Also I noticed that new version of Blogifier won't produce posts with empty cover any more because default value will be saved when I publish a blog. This only influence old blogs when cover might be empty.
So this is a small issue.

**Comment by rxtur** [comment]
No longer relevant after moving to Angular themes
