### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by tawdanst** [blogifierdotnet/Blogifier#155]
I think I'm being a bit dim but how do you actually install this? I came to this from using BlogEngine but I can't seem to figure out how to install this to replace my existing blog

I tried following this video but it didn't work and I couldn't find more recent steps to assist 
https://www.youtube.com/watch?v=vb0lYJKGHSw

Thanks in advance

**Comment by rxtur** [comment]
Start with [setup and troubleshooting steps](https://github.com/blogifierdotnet/Blogifier/blob/master/docs/Troubleshooting.md).

**Comment by tawdanst** [comment]
Not really having much luck, I followed the steps given

Where it says open solution, I go to open it but it can't find the appropriate file to open it as s solution so I opened it as a local folder instead, Once I did that all the files came up in the solution explorer, I set the app.dll file has the startup project and debug on it but got:

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'
