### ISSUE TITLE
Reset blog content to the default one

### ISSUE THREAD

**Issue by KarolPop** [blogifierdotnet/Blogifier#158]
I have installed a Blogifier on herokuapp where I'm testing this app. 
https://blog-karpo.herokuapp.com/
When I have created some new posts and new users all changes have been deleted and the default content displayed. Does somebody know what I'm doing wrong? Did I miss something during the installation?

**Comment by rxtur** [comment]
Make sure you have "SeedData" set to "false" in the AppSettings.json

When true, and there is no users/posts exist, application will seed database with sample data.

Why it thinks there is not users/posts is not clear in your case, could be issue with your connection string or you moved database by accident or it got locked for some reason. In any case, setting SeedData to false should prevent database reset.

**Comment by KarolPop** [comment]
Hi rxtur,
Sorry I'm replying to your comment so late but only have time now to do it.
I see, the "SeedData" is set to false and the issue is still occuring. 
https://github.com/KarolPop/personal-blog/blob/master/src/App/appsettings.json 
The connection string seems to be ok. Any other idea what can be wrong here?

Thnx in advance for help :)
