### ISSUE TITLE
Multi-Language Support

### ISSUE THREAD

**Issue by ureymutuale** [blogifierdotnet/Blogifier#159]
Hello, I started using Blogifier last week and im loving it.

I would like to point that this is a feature suggestion.
I use the blog for our company tech blog and because we are a bilingual company and website, 
I would like to request a multi-language contents support, when writing creating/editing posts,
Basically having the same posts but with contents in different languages.
I think this would be a great feature for your next release.

**Comment by farzindev** [comment]
Blogifier has changed and improved a lot since 2019.
This would be a great idea, but for now, we are trying to make the basic and necessary features more stable.
Also, we are localizing as we go.
