### ISSUE TITLE
Files Pagination

### ISSUE THREAD

**Issue by farzindev** [blogifierdotnet/Blogifier#16]
In the Edit Files, we have Pagination that belongs to the Files list, that shouldn't be in the Edit Files.

**Comment by rxtur** [comment]
The only pagination I see in the editor page is for file picker and should be there. Not clear on "edit files" - is it editor page? Files page?

**Comment by farzindev** [comment]
No in the [files](http://blogifier.azurewebsites.net/admin/files), when you click on any image to delete it.
you can see a pagination.

**Comment by rxtur** [comment]
Fixed.
