### ISSUE TITLE
Ability to configure Markdig.MarkdownPipelineBuilder

### ISSUE THREAD

**Issue by arcrook** [blogifierdotnet/Blogifier#160]
Hello

This is a great framework. While exploring its capabilities I found the limitation that you cannot render tables by default.

I know you can write a table in the native HTML within the markdown file and this will render (#152). However, this is not the most convenient for my scenario. I have a lot of tables and the tables are in pipe format.

I noticed the markdown editor in preview will render pipe tables correctly. However, when the post is saved and published the table renders as a paragraph `<p></p>`.

This is because by default, without any options the use of Markdig within the PostController is using the plain CommonMark parser:
```
model.Post.Content = Markdown.ToHtml(p.Content);
```

In order to activate most of all advanced extensions like table rendering, a MarkdownPipelineBuilder has to be initialized:

```
var mpl = new MarkdownPipelineBuilder().UsePipeTables().UseAdvancedExtensions().Build()
model.Post.Content = Markdown.ToHtml(p.Content, mpl);
```
There is no way to inject a `MarkdownPipelineBuilder` into Core.Api to change the default behaviour.

I would like to suggest a feature to be able to configure the MarkdownPipeline for the next iteration. Default would be plain CommonMark parser. But if I, say, registered a `MarkdownPipelineBuilder` with the DI `IServiceCollection` it would use this for parsing.

Thanks for reading,

**Comment by rxtur** [comment]
I did not know about that, need to take a look, thanks for a pointer.

**Comment by rxtur** [comment]
Implemented, may do a configuration later if needed.
