### ISSUE TITLE
 Сonfigure theme

### ISSUE THREAD

**Issue by Farrell23** [blogifierdotnet/Blogifier#163]
Hello, could you help to configure a project with a theme. I used the guide, but even if I build it, an error comes out. Thank.

**Comment by rxtur** [comment]
Sure, but you need to be more specific about that error or point me to the theme if it is public.

**Comment by Farrell23** [comment]
@rxtur I followed this tutorial - http://rtur.net/posts/angular-theme-for-blogifier-jump-start
I created an application and launched it.
but when I copy files from the themes-master \ archived \ wwwroot-themes \ vision folder to the myapp \ src \ assets folder, such an error crashes 
![Clip2net_190831132141](https://user-images.githubusercontent.com/14282122/64062697-80816a80-cbf2-11e9-9cbf-81dc04911488.png)
Error in rxjs-compat / Subscription, as I understand it

**Comment by Farrell23** [comment]
@rxtur Maybe I'm missing something?

**Comment by rxtur** [comment]
I'll convert vision theme and see if I run into this issue.

**Comment by rxtur** [comment]
I added "vision" to built-in themes and pushed it to demo site at blogifier.net. Haven't ran into errors, sometimes you just need to run "npm install" again from VS terminal to refresh npm modules and it fixes it.

**Comment by Farrell23** [comment]
@rxtur Ohh, thx. I'll check you code and will write to you. Very thanks for you time and help :D

**Comment by Farrell23** [comment]
@rxtur Sorry to bother you, but I tried all the options, but for example the theme "moments" , I can’t recreate it as in the screenshot. Tell me, what am I doing wrong? Most likely I do not have the correct layout for the app folder. I would like to ask you, could you configure the theme of "moments". I would be very grateful. My email address is vadim_lost@outlook.com

**Comment by Farrell23** [comment]
@rxtur src / app would be enough for me, since assets already have. Thanks)

**Comment by rxtur** [comment]
I'm going to convert all archived MVC themes to Angular, so just check back, shouldn't take long - they very similar in structure.

**Comment by Farrell23** [comment]
@rxtur Is there any plan for releases or versions? since your project has inspired me very much and I would like to popularize such a resource in my country. Having recorded tutorials or video materials for Russian speakers)

**Comment by rxtur** [comment]
The short plan is:

1. convert all themes so people moving from previous versions have no or few problems upgrading. Should take a week or two.

2. release v.2.5 with Angular front-end, definitely before end of September.

3. Add bunch of Youtube videos with instructions on front-end development and customization.

**Comment by Farrell23** [comment]
@rxtur That sounds cool. Can I help you with something? I would be happy to help the project.
