### ISSUE TITLE
Blogifier.Core nuget package still supported?

### ISSUE THREAD

**Issue by Xhanti** [blogifierdotnet/Blogifier#167]
Hi,

Is embedding Blogifier.Core in an ASP.NET Core application still a supported scenario?

I have a personal website that I want to add a blogging component to and want to use this [package](https://www.nuget.org/packages/Blogifier.Core/1.4.8-beta)

[This](http://rtur.net/posts/consolidating-blogifier-and-core) blog post on the other hand leads me to believe that this is not a supported scenario, seeking confirmation?

Regards

**Comment by rxtur** [comment]
It haven't stopped working, so you can use it, but it is no longer developed. Was too much to handle :)
