### ISSUE TITLE
Trouble with some admin settings

### ISSUE THREAD

**Issue by rdalkire** [blogifierdotnet/Blogifier#170]
I log in as admin, and I can change the title and description, but then I am *not* able to reliably change the site icon or cover image (after several attempts I somehow randomly got the cover image to change but not the icon).  Are the "select" buttons grayed-out for some reason, or do they just happen to be gray? Here's how I was trying to do it.:

1. Navigate to Admin (sign in as admin if required) > Gear ("Settings") > General
1. Select a new Logo Image.
1. Upload and select.

Expected result: The path to the Logo Image should be updated to whatever you selected. When you click "save" then visit the blog, you should see the new logo instead of the fancy "B".

Actual result:  From Edge I see a flash of a red "Requested JSON parse failed." box, though from Chrome it shows green "updated" box.   Afterward, from either browser the path is still the same and so is the logo. 

I'm not seeing any errors or warnings in the visual studio output window or the logs.

[blog settings screen snippet](https://www.dropbox.com/s/z433x9nrzrdzfiv/BlogSettings%202019-09-28%20171850.png?dl=0) (dropbox)

Also I'm unable to remove the facebook social icon.  I tried to remove the node highlighted in the image below but when I click 'save' and refresh the blog itself the icon is still there.  I go back to the theme settings again make sure my 'save' took, and the json was changed OK.

[blog theme icons json dialog](https://www.dropbox.com/s/rt1qzb4d95iypoa/BlogThemeSocials2019-09-28%20171850.png?dl=0) (dropbox)

I also tried to edit the facebook node so that it points to my own personal facebook profile instead of blogifier's; that didn't work either.

I have tried in the following environments, from Chrome, Edge and Internet Explorer (I don't really care about whether it works in IE; I was just hoping to get it done somehow)   
- The demo site at blogifier.net
- The latest source code (head of master at the date of this edit, 9/28/2019) running from within VS 2019 on Windows 10 with the default settings (SQL Lite and so forth) by simply setting "App" as the Startup Project then clicking the "IIS Express" launch button
- Deployed and running behind nginx on MacOS against a Postgres database.

**Comment by rxtur** [comment]
This should work now except Edge. Edge doesn't like `function.name` in callbacks, will add work around some time tomorrow.

**Comment by rxtur** [comment]
Fixed for Edge too.
