### ISSUE TITLE
Social buttons issue

### ISSUE THREAD

**Issue by rdalkire** [blogifierdotnet/Blogifier#171]
User Action:
1. Navigate to Admin (Log in as admin if you haven't already) > Themes > Settings of current theme
1. Modify the JSON so that, for example, the facebook link goes to some other facebook page

```
{
	"socialButtons": [
		{
			"link": "https://www.facebook.com/recreationalmath",
			"icon": "fa-facebook"
		},
...
```

3. Save your changes then click the "visit blog" icon to go back and look at the results.  Mouse-over the facebook icon to examine the URL it  points to.

Expected result:  The facebook link icon should point to the recreationalmath page or whatever you chose.

Actual result:  The link still points to the blogifier facebook page

Environment:  Blogifier v.2.5.02, at the demo site or built as-is in visual studio.  Any environment, as far as I know.

**Comment by rxtur** [comment]
If you switch to standard theme, you'll see everything is working as expected. Other themes haven't been updated yet, mostly because there theme settings page in the works replacing JSON file, with form fields etc. All will be updated soon.
