### ISSUE TITLE
Does not run on Azure App Service Linux

### ISSUE THREAD

**Issue by timheuer** [blogifierdotnet/Blogifier#173]
Blogifier fails to run on Azure App Service Linux.  Errors are in SQLite being locked.

**Comment by farzindev** [comment]
A lot has been changed since 2019,
And now we are working on the [version 3.0](https://github.com/blogifierdotnet/Blogifier/projects/1),

Please try the latest stable version or the latest source code.
Also you can [take a look at the demo](https://demo.blogifier.net).
