### ISSUE TITLE
SSR/SEO

### ISSUE THREAD

**Issue by 8VAid8** [blogifierdotnet/Blogifier#174]
Does Blogifier supports SSR? I tried to run a blog and found that it is rendered on a client. What about SEO. Could it be SEO-friendly?

**Comment by forconz** [comment]
There are 2 major ways to resolve the SEO issues being faced in the Blogifier.
1. Isomorphic Javascript technology
2. Prerendering

Building Single Page Applications on ASP.NET Core with JavaScriptServices
https://devblogs.microsoft.com/aspnet/building-single-page-applications-on-asp-net-core-with-javascriptservices/

**Comment by seebosmile** [comment]
most asp.net core hosting provider not install Node.js on the server,  this is cons of Blogifier

**Comment by rxtur** [comment]
Right now there two versions, one is MVC with server-side rendering.
