### ISSUE TITLE
Math formula rendering support

### ISSUE THREAD

**Issue by hez2010** [blogifierdotnet/Blogifier#176]
## Support Math Formula
Math formulas:
$ \sum_{i=1}^{n} {i^2+3} $
$$ \sum_{i=1}^{n} {i^2+3} $$

I think you can use [katex](https://katex.org/) to support tex math formula

**Comment by mwroffo** [comment]
I would love to see this as well. @hez2010 have you tried to implement this? If not I'm open to giving it a try.

**Comment by hez2010** [comment]
@mwroffo Currently I'm not working on this.

**Comment by farzindev** [comment]
A lot has been changed since 2019,
This is a great idea, but as of right now there are many fundamental priorities that we have to take care of.

So I'm going to give this a Feature label and take a look at it for the next version.
