### ISSUE TITLE
SingIn - Authorization error

### ISSUE THREAD

**Issue by badozvora** [blogifierdotnet/Blogifier#184]
Hi guys,
I downloaded Blogifier and I run it locally as sugggested into site guide.
When I try to access to Admin area it requires login and I used following credentials:

**Username: admin
Password: admin**

but it doesn't redirect to Admin area, it reloads login page, without errors.
In the output panel I can see following message:

**Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed.**

What am I doing wrong?

Thanks in advance for your help

**Comment by rxtur** [comment]
Sometimes getting it with SQLight database corrupted while moving around. It gets cached or otherwise loosing its data. Usually fix it by refreshing database from source.

**Comment by badozvora** [comment]
Hi rxtur, thanks for your answer.
I debugged the login operation but credentials are correct and the check into database is executed withouterrors.
After checking login it tries redirect to requested url but it doesn't happen and the error in the output panel is:

Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed.

Can be really a database problem?

**Comment by rxtur** [comment]
This seems like very isolated case that we can't reproduce to be able to fix.
