### ISSUE TITLE
Exception when starting project

### ISSUE THREAD

**Issue by neo302** [blogifierdotnet/Blogifier#185]
I downloaded the project from the master branch and when I start the project, it hits an exception on the Core.AppConfig  GetAssemblies method on line:

var product = assembly.GetCustomAttribute<AssemblyProductAttribute>().Product;

The error:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

The product is: "Serilog.Extensions.Logging"
Assembly: {Serilog.Sinks.File, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10}

Thank you

**Comment by rxtur** [comment]
This code is for side-loading plugins, it is within try/catch and should not be a problem. Current code is not using plugins out of the box, so you can comment out code in question if needed.

**Comment by neo302** [comment]
Thank you!
