### ISSUE TITLE
Administrative pages don't populate

### ISSUE THREAD

**Issue by krjii** [blogifierdotnet/Blogifier#186]
Deployed app to iis server. Everything seems to work fine. The problem comes when logging in and accessing the administrative pages. I do not get an error message but the pages do not populate. The only things that shows on the page is the left most toolbar for selecting theme, settings, etc.

Any idea why the pages aren't populating? I can't see theme options, i can't create users, i can't do anything that a logged in user would do.

**Comment by rxtur** [comment]
First of all, check [troubleshooting](https://github.com/blogifierdotnet/Blogifier/blob/master/docs/Troubleshooting.md) section. Common issues are related to database publishing - default SQLite database not copied to the server, does not have write permissions etc.

**Comment by krjii** [comment]
Checked troubleshooting, I connect to a db on a remote server. That seems to be configured properly. The main page seems to load just fine with the 2 posts I have saved. Just no admin pages. I can type in the passwords and that's all fine.

**Comment by rxtur** [comment]
The troubleshooting asks to provide steps to reproduce the error, or at least to understand your environment. When you saying "I connect to db or remote server" I'm completely at lost - it could be you connected to PostgreSQL on Arch Linux and I'm suggesting to check permissions for IIS identity. I don't even know if you tried to publish to local and if it worked for you. And if you using remote db - did you try to run in VS pointing to that remote db?
