### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by gkaya** [blogifierdotnet/Blogifier#188]
Hi,

/feed/rss

doesn't return anything, just an empty page. 

It seems to work fine on the demo portal, what could have gone wrong? 
I'm using std theme at the moment. 

PS: I have webdav activated on the server but it is disabled for this website and also specifically removed in the web.config which eliminated other webdav related problems, so I don't think it is related with webdav.

BR
Gokhan

**Comment by rxtur** [comment]
Fixed with [latest update](https://github.com/blogifierdotnet/Blogifier.SPA/commit/e845f256ad03c7ea75796eba0752b57914e03a18).
