### ISSUE TITLE
Author is null on demo site when switching between themes.

### ISSUE THREAD

**Issue by jwmxyz** [blogifierdotnet/Blogifier#189]
- This is a breaking change.

**Steps to reproduce:**

- Navigate to [http://blogifier.net/admin/settings](http://blogifier.net/admin/settings)
- Change theme from `standard` to `cleanblog`
- Save
- Signout
- Navigate to [http://blogifier.net/admin](http://blogifier.net/admin)
- Page is blank and app crashes.

**Cause:**

Inside of `Profile.Razor.cs` Author is null:

```
 public async Task Load()
 {
        var authState = await AuthenticationStateTask;
         Author = await DataService.Authors.GetItem(
              a => a.AppUserName == authState.User.Identity.Name);
          PwdModel = new ChangePasswordModel {
                UserName = authState.User.Identity.Name
          };
 }
```

**Fix**
- Navigate to [http://blogifier.net/account/login](http://blogifier.net/account/login)
- Change the theme back

**Comment by rxtur** [comment]
Thanks for pointing this out, it should redirect to login screen now as expected.
