### ISSUE TITLE
blog route

### ISSUE THREAD

**Issue by murst** [blogifierdotnet/Blogifier#19]
1, There should be a way to set `Constants.BlogRoute` from the web application. Perhaps move it to AppSettings.json?

2. Admin view: The "View" button in the post editor has a hard-coded 'blog/' path (inside 'editorController.js', line 179). This should be the same path as `Constants.BlogRoute`.

3. Admin view: Clicking on the user profile (which opens the options to "View Blog" and "Log Out") and then clicking on "View Blog" navigates to ~/{author slug} . Instead, this should navigate to ~/{Constants.BlogRoute}

**Comment by rxtur** [comment]
#1 - route attribute must be a constant, it has to be determined before any code executes. App settings was first obvious choice but did not work. Probably can be worked with middleware or custom attribute magic, haven't look at it yet.

#2 - yes, should be fixed. Will need to pass it to JS.

#3 - default configuration is multi-blog, for blogger "view blog" means opening own blog, not shared/home page.

**Comment by murst** [comment]
Here's a commit w/ what's needed to move BlogRoute into `ApplicationSettings`.

Anywhere where `Constants.BlogRoute` is being used would also need to be updated.

https://github.com/murst/Blogifier.Core/commit/0e1c64052e1f221f0043581f83eed8527c9aced3

**Comment by murst** [comment]
#3 - I think I misunderstood the point of the author page. I initially thought that it was simply meant as a filter to get all posts by that author (similar to categories). However, the more I look at it, authors have their own theme settings, etc.

**Comment by rxtur** [comment]
Yes, kind of what I was hoping for. Updated.
