### ISSUE TITLE
Cannot Access Newsletter Page

### ISSUE THREAD

**Issue by Xaninho** [blogifierdotnet/Blogifier#191]
Hey everyone! First of all, as this is my first issue here, thank you for making this repository available for everyone, it's a pretty cool resource to help learning the ASP.NET Core framework 😅

I've cloned this repository, and changed the appsettings.json to use SqlServer. When I run the project, the database is succesfully created. However, as I'm exploring the project, when I click the "Newsletter" tab in the Admin Dashboard, I get this error:

![imagem](https://user-images.githubusercontent.com/52694651/80711264-fcb4b080-8ae7-11ea-866a-072f440c3d08.png)

![imagem](https://user-images.githubusercontent.com/52694651/80711298-0b9b6300-8ae8-11ea-8091-45f753c2a107.png)

Any thoughts on what happened? The only changes I've made is in the appsettings.json file, and the database appeared to be created succesfully.

**Comment by rxtur** [comment]
Actually, scratch below - seems like issue with different database behaviors, works for SQLite but not for SQL Server: "Cannot specify a column width on data type text". I'll check out why SQL Server is not happy.


First, check if you need to update Blogifier.Core nuget package - there should be migration adding columns to newsletters table.
Blogifier checks for migrations in the program.cs on app start and runs migrations automatically, so you can check with debugger if it finds any new migrations and if there any issues executing them.

**Comment by rxtur** [comment]
Fix been applied with latest update, newsletter migration script should work with SQL Server now.

**Comment by Xaninho** [comment]
That does it. Thank you for the quick support! 😊
