### ISSUE TITLE
Clean Installation problem with this new version

### ISSUE THREAD

**Issue by gkaya** [blogifierdotnet/Blogifier#197]
Hi,

There are a lot of improvements and fixes so I decided to make a fresh installation.
Downloaded compiled and published the code, uploaded to PRD folder.
Replaced the connection string from my old config file.
Deleted the old database.

1) When I seed the data, I can see the tables created and I also see the admin user added to users table. But there are no sample posts created, it is just empty.
2) I can successfully login to admin but none of the functionalities are working. I cannot create a new blog post. If I try to change the theme, page refreshes but setting change is not applied, returns back to default theme.

Thanks in advance.
Br
Gokhan

**Comment by jwmxyz** [comment]
Hi @gkaya,

Are you using SqlServer?

Have you followed the advice given in the [troubleshooting doc]( https://github.com/blogifierdotnet/Blogifier/blob/master/docs/Troubleshooting.md)?

**Comment by gkaya** [comment]
Yes I'm using SqlServer.
SQL user and other settings are all good, those are reused and was working fine in previous installation.

I also tried with default sqllite installation. Problem 1) does not exist, I can see the sample posts, Problem 2) persist, I still cannot save/change settings at admin although authentication works flawlessly. 

I can try local installation but that will need a lot of configuration and will be time consuming. 

PS: I also tried publishing with "portable" and "win64" profiles, same results.

**Comment by gkaya** [comment]
There seems to be a log folder, I was expecting to see some errors generated when I click action buttons from Admin, there was nothing logged to the file.

**Comment by gkaya** [comment]
attaching 40sec video
[2020-05-08_15-06-37.zip](https://github.com/blogifierdotnet/Blogifier/files/4598838/2020-05-08_15-06-37.zip)

**Comment by jwmxyz** [comment]
Hope you dont mind I logged in onto your site from the URL in the video.

It all seems to be working fine on my end. 

You will see I added a test post which I shall delete shortly.

![image](https://user-images.githubusercontent.com/22085211/81404937-930f5480-912e-11ea-8a02-0f95131cbeb0.png)

**Comment by gkaya** [comment]
super, thank you very much, this is a very valuable piece of information.

I'll check with different browsers and laptops, I'll share the results.

PS: I was using latest version of Firefox on Win10.

**Comment by gkaya** [comment]
@jwmxyz  I have tested with my second laptop (again with Win10), all is good. 
on company laptop it doesn't work for some reason. (but was working fine in previous release).
I don't think we need to dig into this, It is probably a network device on company network that is blocking something.
Thanks for the hint.

Btw: sample blog post not seeded to SQL seems still valid but again not a big deal. 
You may want to check that for cosmetic reasons. 

I'll close the ticket now.
