### ISSUE TITLE
I don't see the default admin/admin account.

### ISSUE THREAD

**Issue by dynamiclynk** [blogifierdotnet/Blogifier#199]
Is their a seed script somewhere I didn't find it as part of the EF migration, maybe I am missing something or my setup is wrong.

I am using MYSQL.

I checked the AspNetUsers table it is empty.

**Comment by dynamiclynk** [comment]
I thought the migrations didn't execute but they did but the admin/admin user is missing. AspNetRoles is also empty I am able to create a user that has IsAdmin=true in the Authors table but the admin View is not providing much interaction with the blog itself.

**Comment by rxtur** [comment]
The seed data with default admin account is for demo purposes only. When you start new blog from scratch, you just register new account using actual blogger name and start building your own content.

**Comment by dynamiclynk** [comment]
I did that but is there an interface to add roles because the interface I see only let's me modify the current user

May 16, 2020 13:10:07 rxtur <notifications@github.com>:

**Comment by rxtur** [comment]
> Blogifier is a single-user personal blog...
> 
> If you are looking for a multi-user Angular version of Blogifier, please find it under Blogifier.SPA repository.

**Comment by dynamiclynk** [comment]
Ah ok thank you.

May 16, 2020 13:16:28 rxtur <notifications@github.com>:

**Comment by rxtur** [comment]
No problem, glad to help.
