### ISSUE TITLE
Post subtitle or description

### ISSUE THREAD

**Issue by murst** [blogifierdotnet/Blogifier#20]
It would be nice if there was an option to provide a subtitle or description for a blog post. If this value is set, the post list would display this value instead of just selecting the first 300 characters of the blog post.

**Comment by rxtur** [comment]
Francis, can you think of a good way of adding text area to the post for this? Maybe, another button next to post image and categories,  or even make it drop-down if 3 buttons too much, specially in mobile. Or some other way - we just need a text area where user can modify post description by hand.

**Comment by farzindev** [comment]
Well, We can add a textarea to the post.
But I guess by default we should put the first 300 characters. if the author didn't fill it. Also, we need it for meta description in the `<head>` tag for each post.

We have to move cover and categories and this textarea to a Bootstrap's Modal. also in future, we can add more tools like Custom Fields or edit date or etc, to this Bootstrap's Modal.

**Comment by rxtur** [comment]
Yes, and I'll take care of back-end to populate and save data, just need UI updated.

**Comment by farzindev** [comment]
@rxtur Done.

**Comment by rxtur** [comment]
Completed.
