### ISSUE TITLE
GitHub post sync

### ISSUE THREAD

**Issue by IeuanWalker** [blogifierdotnet/Blogifier#203]
Hi, this is a suggestion.

It would be amazing if blog posts could be synced to a GitHub repo.
A bit like this plugin created for Wordpress - https://github.com/mAAdhaTTah/wordpress-github-sync

This would allow anyone that sees and issue in a blog post to submit a PR and once approved will automatically update the blog. 
Obviously this will automatically add versioning to blog posts and act as a backup.

**Comment by rxtur** [comment]
I guess it can be done similarly as a plugin doing push/pull between blog and Github, just not sure how much demand this would have. Personally I would like a backup feature. There is Github integration already in the services layer and plans to use it more for things like documentation, theme store etc. so it would line up with general direction, so maybe.

**Comment by farzindev** [comment]
Close this for now. we review this for the next version.
