### ISSUE TITLE
Basis for full site?

### ISSUE THREAD

**Issue by tinmac** [blogifierdotnet/Blogifier#208]
Hi

Advice needed please.

As a blog is never really on its own, we want to have other pages too (eg sales landing page or an admin area).

Would you say its best to use blogifier in an untouched state (in a sub folder with its own reverse proxy to mysite.com/blog) and also a separate main .net core web site for our landing pages and user/admin login area using identity (mysite.com).

Or are we encouraged to incorporate our pages into the blogifier project via MVC or Pages, eg landing pages for sales? 

And can we add identity to the blogifier project via the scaffolding without interfering or breaking blogifier ?

**Comment by rxtur** [comment]
If all you need is a limited number of pages then doing it within Blogifier itself is perfectly fine. But if it is more like a full-blown site with a blog then separating probably will work best.

Blogifier currently uses standard cookie-based forms authentication that VS enables out of the box, that should work in most cases even if you run in the sub-folder. There plans to use JWT bearer authentication to support APIs and later web assembly Blazor, but right now it is as simple as it gets.

**Comment by tinmac** [comment]
Thanks @rxtur  that makes sense.

If I do wish to have the blog site as the home of the web app (ie not bother with /blog), how do I do this?

**Comment by mwasplund** [comment]
This project looks promising to incorporate into my personal website, but I would much prefer to have a nuget package that injects the blog functionality during ASP.Net setup instead of having to replace my entire site with the one in this repo.
