### ISSUE TITLE
Import BlogML OPML

### ISSUE THREAD

**Issue by Geekays** [blogifierdotnet/Blogifier#209]
A great blog app. I am replacing my blogengine.NET with this now.

But how to migrate the data from the earlier one to this? any BlogML export/import?

**Comment by rxtur** [comment]
You should be able to pull RSS feed from Blogengine to [Blogifier.SPA](https://github.com/blogifierdotnet/Blogifier.SPA) version [using this](https://github.com/blogifierdotnet/Blogifier/blob/master/docs/Import.md).
The resulting database should work fine for any Blogifier flavor, including Blazor/MVC.

**Comment by Geekays** [comment]
> 
> 
> You should be able to pull RSS feed from Blogengine to [Blogifier.SPA](https://github.com/blogifierdotnet/Blogifier.SPA) version [using this](https://github.com/blogifierdotnet/Blogifier/blob/master/docs/Import.md).
> The resulting database should work fine for any Blogifier flavor, including Blazor/MVC.

I tried that and raised another issue in [Blogifier.SPA](https://github.com/blogifierdotnet/Blogifier.SPA) 

I see Error 500. Attached the log file in that issue already.
