### ISSUE TITLE
SSL in theme Paperkit does not work

### ISSUE THREAD

**Issue by MadeInOzzie** [blogifierdotnet/Blogifier#219]
Hello, Thank You for the great product!

I have been using Paparkit Theme, and recently installed a SSL Certificate. After installing the Certificate, all that renders on the page is the Footer.

![Footer Render after install of SSL](https://user-images.githubusercontent.com/72710362/97789825-60db3d00-1c0f-11eb-96bf-9186101c0893.png)

I would be very pleased to fix this issue as I have spent a long time modifying this theme for my purposes.

Again, Thank You all so much! I very much appreciate your effort on this product!

If I enable Standard Theme, the page renders as one would expect.

Chris

**Comment by MadeInOzzie** [comment]
12 days ago, no response? Would be great to at least have a pointer in the right direction.

**Comment by farzindev** [comment]
We are working on the [Blogifier v3.0](https://github.com/blogifierdotnet/Blogifier/projects) and themes structure have been changed a little bit.
We'll make a few free themes similar to Paperkit and publish it separately after the Blogifier v3.0 has been released.
