### ISSUE TITLE
Theme Settings

### ISSUE THREAD

**Issue by murst** [blogifierdotnet/Blogifier#22]
I thought it'd be useful to be able to configure a theme from the _appsettings.json_ file (so that if someone downloaded a blog theme, they wouldn't have to go into the html/javascript for some basic settings).

I created a couple properties (`Dictionary<string, string>`) called `BlogThemeSettings` and `AdminThemeSettings` in `ApplicationSettings`, and populate it from _appsettings.json_.

In _appsettings.json_, I now have the following: 

`"BlogThemeSettings": {
      "FeaturedPosts":  2,
      ...
    }`

The changes were relatively minor and I'm certainly open to doing this in other ways (I could, for example, create a JS file in my theme where all of the settings are if you guys don't want this in the _appsettings.json_ file). The changes I've made are available in a commit: https://github.com/murst/Blogifier.Core/commit/a146424ba057a4a0ffc7c4344b885f02a761a3dc

**Comment by rxtur** [comment]
In the next version site admin will have dedicated dashboard to manage application, profiles and so on. Current app settings mostly placeholder.
