### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by filjan** [blogifierdotnet/Blogifier#221]
I downloaded the code, created a SQL Server database, set appsettings.json so this will work with SQL Server. The program runs and seems to work fine. When I try the login with admin/admin I am getting the error:

 System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Blogifier
  StackTrace:
   at Blogifier.Components.Dashboard.CustomWidget.<OnInitializedAsync>d__20.MoveNext() in C:\Blogifier-master\src\Blogifier\Components\Dashboard\CustomWidget.razor:line 68

**Comment by odukes** [comment]
I got as far as you did but the database you created is empty hence you might have to register a new user. I did however, the login page redirects back to itself after a successful login

**Comment by miguelEsteban** [comment]
Need to populate CustomFields table.

INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
1,0,'blog-title','Blog');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
2,0,'blog-description','Short blog description');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
3,0,'blog-items-per-page','10');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
4,0,'blog-cover','data/admin/2020/4/cover.jpg');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
5,0,'blog-logo','data/admin/2020/3/logo-white.png');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
6,0,'culture','es-ES');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
7,0,'blog-theme','cleanblog');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
26,0,'admin-dashboard-sidebar',' ![admin/img/cover-small.jpg](/admin/img/cover-small.png)
<ul class="bf-list bf-posts-list d-block" aria-label="drafts">
	<li class="bf-list-item d-flex align-items-center">
		<a class="bf-list-item-link" target="_blank" href="https://github.com/blogifierdotnet/Blogifier.Blazor">Source Code (Github)</a>
	</li>
	<li class="bf-list-item d-flex align-items-center">
		<a class="bf-list-item-link" target="_blank" href="http://blogifier.net">Demo Site</a>
	</li>
</ul>
<hr />
<p style="font-size: .95em">Here you can add your own Markdown or HTML markup, whatever makes sense for you. For example, add your Host information, bookmarks related to your blog etc.</p>');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
27,0,'disqus-key','<script>
  (function () {  // DON''T EDIT BELOW THIS LINE
    var d = document, s = d.createElement(''script'');
    s.src = ''//blogifierdotnet.disqus.com/embed.js'';
    s.setAttribute(''data-timestamp'', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
28,1,'facebook','blogifierdotnet');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
29,1,'twitter','blogifierdotnet');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
35,1,'github','blogifierdotnet/Blogifier');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
40,0,'social|facebook|1','http://your.facebook.page.com');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
41,0,'social|twitter|1','https://twitter.com/blogifierdotnet');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
42,0,'social|github|3','https://github.com/blogifierdotnet/Blogifier');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
43,1,'social|facebook|2','https://www.facebook.com/blogifierdotnet');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
44,1,'social|twitter|1','https://twitter.com/blogifierdotnet');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
45,0,'disqus-site-key','blogifierdotnet.disqus.com');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
46,0,'blog-include-featured','True');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
47,0,'blog-header-script','');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
48,0,'blog-footer-script','<script>
  (function () {  // DON''T EDIT BELOW THIS LINE
    var d = document, s = d.createElement(''script'');
    s.src = ''//blogifierdotnet.disqus.com/embed.js'';
    s.setAttribute(''data-timestamp'', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<script id="dsq-count-scr" src="//blogifierdotnet.disqus.com/count.js" async></script>');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
49,0,'email-selected-provider','SendGrid');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
50,0,'email-sendgrid-api-key','');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
51,0,'email-sendgrid-configured','False');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
52,0,'email-mailkit-name','');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
53,0,'email-mailkit-address','');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
54,0,'email-mailkit-server','');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
55,0,'email-mailkit-port','0');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
56,0,'email-mailkit-configured','False');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
57,0,'email-mailkit-password','');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
66,0,'email-from-email','admin@blog.com');
INSERT INTO [CustomFields] ([Id],[AuthorId],[Name],[Content]) VALUES (
67,0,'email-from-name','administrator');

**Comment by farzindev** [comment]
A lot has been changed, and we are working on the Version 3.0,
We have removed the Custom Widget form the Dashboard,
Please take a look at the latest source code.

or you can take a look at the demo:

https://demo.blogifier.net/
