### ISSUE TITLE
Admin in new theme

### ISSUE THREAD

**Issue by Whisperes** [blogifierdotnet/Blogifier#231]
Error when try to login.

**Comment by farzindev** [comment]
It would be great if you provide more information.

**Comment by yourstockforecast** [comment]
How do I login with fresh install.

**Comment by farzindev** [comment]
on the latest source:
username: admin@us.com
password: admin

If the project is published, on the first login, user gets redirected to the /admin/register page to register a new account. Once account created, registration page is disabled and this user becomes a blog owner.
