### ISSUE TITLE
BlogController > Index : Custom fields are always an empty dictionary

### ISSUE THREAD

**Issue by murst** [blogifierdotnet/Blogifier#26]
On the Index page, the BlogController never populates the CustomFields. It is always an empty dictionary.

**Comment by rxtur** [comment]
There are no global, application-wide custom fields. Currently, only profile (blog) and posts have custom fields, they used for blogger custom code, social buttons and post comments. Nothing to populate for index page.

**Comment by murst** [comment]
I think there needs to be something on a global basis. For example, in single-blog mode, the index page is the blog page.  Also, there needs to be a place where tracking code, global styles, etc, can be added. 

I like that we can add custom themes and custom code to profiles, but since there is also a global theme, there should be global custom code.

It should also be more clear in the settings that the current head, post, and footer settings apply to profile only. Right now, they are in a separate section from profile, which made me think that they were not directly associated w/ the profile.

**Comment by rxtur** [comment]
I'm just saying there is no global custom fields now, this is why it is empty. Things will change.
