### ISSUE TITLE
Published and Modified Date

### ISSUE THREAD

**Issue by farzindev** [blogifierdotnet/Blogifier#260]
## Published and Modified Date
We need to have the published and modified date of the posts and pages!

**Use Case**
- We can use it in the theme that when it was published and when it was modified.
- [Google Structured Data](https://developers.google.com/search/docs/data-types/article#examples) need the published and modified date! so they can tell if a post has been updated or not on the search results!
- And more...

## The Real Question
Do we update the modified date every single time that user hits the Save button (assuming it was published before) and do we move the post to the top of the list or not!?

## Why this is important

**Scenario one**
I wrote an article and published it a week ago. now I want to update the cover! or add a new category to it. so basically no changes to the context of the article!

In this case, I don't want to move the post to the top of the list!

**Scenario two**
I wrote an article about something and after 6 months, I found another approach and I want to share it with my readers.
and I don't want to publish a new article about it, I just want to add the new content and update it. 

In this case, I want to move the post to the top of the list!

**How to implement this**
If a post has been published already and I edited it and then I hit the save button,
Blogifier asks me to move the post to the top of the list and change the modified date to the current date or not.

**We can have settings for this**
- Ask every time.
- Move to the top of the list.
- Don't move to the top of the list.

## What do you think?
Please let us know what you think.
Thank you.

**Comment by rxtur** [comment]
We do have dates for created, published and modified - check [post model here](https://github.com/blogifierdotnet/Blogifier/blob/main/src/Blogifier.Shared/Domain/Post.cs).

I think, best way to handle this in the theme is to use `IsFeatured`.
If you want old post to go on top, set it as featured. When it is no longer important, remove from featured and it goes away.
Given, theme handles it properly.

**Comment by farzindev** [comment]
Great.
