### ISSUE TITLE
App have issue running against .NET 6 Preview 3 or later as "System.Drawing.Common" removed from Microsoft.AspNetCore.App shared framework

### ISSUE THREAD

**Issue by CancanTang** [blogifierdotnet/Blogifier#268]
Hi, there is change about "Some assemblies removed from Microsoft.AspNetCore.App" in .NET 6 Preview 3 which will effect your app when running against .NET 6 Preview 3 and later, for details, please discussion see in https://github.com/dotnet/aspnetcore/issues/31387. You might need add a PackageReference to the affected project for the removed assemblies.

**Comment by rxtur** [comment]
We'll be supporting 6 after it's final release.
