### ISSUE TITLE
Customizing Views

### ISSUE THREAD

**Issue by Nikkinoodl** [blogifierdotnet/Blogifier#27]
Awesome project, RTur - it worked right out of the box for me. As a BlogEngine.NET user for 6 years, I came to appreciate the quality of that app and I'm delighted that you've started this new project.

My question is about customization of the views. Once the Nuget package is installed and the settings changed to "CUSTOM", do I need to do anything more to set up custom views. I copied the Blogifier/Blog and Blogifier/Admin views over from the WebApp sample to my own app, but it still seems to be running the views in the core module. What am I missing?

Please let me know if I can help with this project to pay back for your efforts over the years. I don't think anyone would want to run any code that I've written, but I'd be glad to help with documentation, if needed.

Many thanks!
Simon

**Comment by rxtur** [comment]
Hi Simon,

when you copy views into "Views/Blogifier/Blog/Custom", the "Custom" theme will pop up in the blog settings. So you can select this theme for your blog. 

For admin, you would need to add it to appsettings.json as "AdminTheme": "Custom".

**Comment by Nikkinoodl** [comment]
Thanks for your help! My problem was that I didn't have my own Blogifier settings in appsettings.json. That meant that I was trying to run a multiple blog instance, not a single blog.  All the problems cascaded from that.

Fixed now.  Looks great!
