### ISSUE TITLE
version 3 publish date

### ISSUE THREAD

**Issue by amira133** [blogifierdotnet/Blogifier#273]
I want to know when the release date of version 3 is?
also do you support Right to left language support in version 3?

**Comment by farzindev** [comment]
There are a few things left to do,
but hopefully, in less than a month, we release version 3.0 with RTL.

We are using the Bootstrap 5 beta 3 which comes with the RTL.
But we have to wait until [they release the stable version](https://github.com/twbs/bootstrap/projects/27). which it will be any day now.

Subscribe to the Blogifier newsletter, we'll notify you:
https://blogifier.net/

**Comment by amira133** [comment]
thanks alot
