### ISSUE TITLE
Would you like me to help you?

### ISSUE THREAD

**Issue by amira133** [blogifierdotnet/Blogifier#276]
Since I was very interested in your project, I can help add Persian to your project languages or other help. Would you like me to help you in this case or cases?

**Comment by rxtur** [comment]
I think the best way to help in your case would be to add Persian translation and verify LTR functionality. You could work with Farzin on that one. 
The translation functionality in general, both in admin and blog, would be another thing where we could use help - identifying places where we still have hard-coded literals and replacing with translated resources etc.
Any help welcome :)

**Comment by amira133** [comment]
:)

**Comment by farzindev** [comment]
@amira133 Yes, adding the Persian language would be very helpful.
and we are going to update the UI to support the right to left languages. 
so if you add the Persian language, we can test the UI on a real RTL language.

Thank you

**Comment by amira133** [comment]
@farzindev
very well
Can you guide me, where can I add Persian?
Because I'm not very familiar with your structure.
Do you have an Excel or CSV or XML file?
Where is your localization area?

**Comment by farzindev** [comment]
I added the `Resource.fa.resx` file on the dev branch:
https://github.com/blogifierdotnet/Blogifier/blob/dev/src/Blogifier.Shared/Resources/Resource.fa.resx

**Comment by amira133** [comment]
ok, I Done it.

**Comment by farzindev** [comment]
@amira133 Thank you.
