### ISSUE TITLE
Blogifier Running in Production - some notes that might be helpful

### ISSUE THREAD

**Issue by Nikkinoodl** [blogifierdotnet/Blogifier#28]
I've just finished re-launching my blog using Blogifier so that it's now an integrated part of my main website at https://portraitsbysimonbland.com

I wanted to pass on some things that I came across that might be helpful. These are mostly just work-arounds, but I hit a problem with the RSS feed which is worth knowing about in advance.

I'm running this as a single blog application with a custom theme for the blog, standard theme for admin.

1.  In order to keep the same URLs as in BE, and also have the same view functionality, I ended up importing blogifier.core as a project (although there is probably an easier way to do this).

2. I made small changes to PostRepository.cs because I wanted the default page to have the full content of each post, rather than the description.

        private List<PostListItem> GetItems(List<BlogPost> postList)
        {
            return postList.Select(p => new PostListItem
            {
                BlogPostId = p.Id,
                Slug = p.Slug,
                Title = p.Title,
                //Image = string.IsNullOrEmpty(p.Image) ? ApplicationSettings.PostImage : p.Image,  not used
                //Content = p.Description,   replaced this line with the one below
                Content = p.Content,
                Published = p.Published,
                AuthorName = p.Profile.AuthorName,
                AuthorEmail = p.Profile.AuthorEmail,
                BlogSlug = p.Profile.Slug,
                PostViews = p.PostViews
            }).ToList();
        }

3. Commented out this controller:    public IActionResult PostsByAuthor(string slug, int page = 1) because it would otherwise create duplicate URLs for the same content.

4. Modified the categories controller so that the category page URLs will be the same as I had in BE:

    [Route("category/{cat}/{page:int?}")]  //changed this attribute
    public IActionResult PostsByCategory(string cat, int page = 1)  //removed slug parameter
        {
          string slug = "simon-bland";    //added parameter here with my blog name
            var model = _ds.GetPostsByCategory(slug, cat, page);
            if(model == null)
                return View(_theme + "Error.cshtml", 404);
            return View("~/Views/Blogifier/Blog/" + model.Profile.BlogTheme + "/Category.cshtml", model);
        }

5.  Added a bit of custom js because image classes work much better if they are set to img-responsive, also I needed to change the pager hrefs in the category view and this was the easiest way to do it.

$(function () {
    //Change embedded image classes in blog posts to Bootstrap standard
    $('img:not([class=""])').addClass("img-responsive center-block").css('width', '');
    //Change pager button href for category paging
    $('a[href^="/blog/simon-bland"]').each(function () {
        var oldUrl = $(this).attr("href"); // Get current url
        var newUrl = oldUrl.replace("/blog/simon-bland", "/blog/category"); // Create new url
        $(this).attr("href", newUrl); // Set href value
    });
});

6. RSS Import.  When importing from the old BE instance to the blogifier development database I found that I had a few posts with duplicate titles. The import failed after each duplicate was found, but the duplicate record was written to the Blogifier database. When the feed was restarted the first blog post was then duplicated and the feed failed again. I ended up using SSMS to delete all posts directly from the database. After repeating this a few times I was able to clean up the feed by changing the original titles in BE.

7. I couldn't get RSS import to work on my production instance. I probably have too-tight restrictions on what is allowed. The RSS just gives me a message of "Failed" so I'm not sure what is going on. I worked around this problem by scripting the records from the development database in SSMS and imported the records directly into the production database from the scripts.

Hope that helps,
Simon

**Comment by rxtur** [comment]
Cool, glad it worked for you. With RSS, you can export BlogEngine blog into XML file and use it instead of pointing to production site, using file path instead of URL in the import.

**Comment by Nikkinoodl** [comment]
Thanks rxtur.  It's a great piece of software!

I had no idea the RSS import would work with a BlogML file.  Thanks for the tip.

**Comment by Nikkinoodl** [comment]
BTW.  The RSS import failure and 405 Http verb not allowed errors that I was getting in the Admin app were caused by WebDAV being installed on the server (even though it was not enabled!).

After removing WebDAV in the server manager, everything works fine.

**Comment by Nikkinoodl** [comment]
8.  Continuing on from above.  Setting up Blogifier to work with a CDN for static files was fairly easy. 

My CDN distribution reads from the wwwroot of my website.

First, I copied all Blogifier static content to my wwwroot directory.

Using a custom Blog theme. I just needed to include the CDN versions of CSS and JS files in my custom Blog views. 

Using a custom Admin theme I then modified a couple of FilePickerController.js functions to add my CDN Url to all post cover image and images posted in TinyMCE:

    //Changed function to include CDN source
    function pickPostImgCallback(data) {
        $('#hdnPostImg').val("https://yourCdnUrl/" + data.url); //on this line for Post Cover Images
        editorController.loadPostImage();
        toastr.success('Updated');
        close();
    }

    //Changed Callback function to include CDN source
    function pickCallback(data) {
        if (uploadType === "profilelogo") {
            $('#Logo').val(data.url);
        }
        if (uploadType === "profileavatar") {
            $('#Avatar').val(data.url);

            // TODO: can not access page element from modal
            setTimeout(function () {
                var zzz = $('img.profile-img');
                $('img.profile-img').attr('src', data.url);
            }, 3000);
        }
        if (uploadType === "profileimage") {
            $('#Image').val(data.url);
        }
        if (uploadType === "postImage") {
            setTimeout(function () {
                window.location.href = webRoot + 'admin/editor/' + postId;
            }, 1000); 
        }
        if (uploadType === "editor") {
            if (data.assetType === 0) {
                tinymce.activeEditor.execCommand('mceInsertContent', false,
                '<img src="https://yourCdnUrl/'       //on this line for post images
               + data.url + '" />');
            }
            else {
                var tag = '<a class="download" href="' + data.url + '">' + data.title + ' (' + humanFileSize(data.length) + ')</a>';
                tinymce.activeEditor.execCommand('mceInsertContent', false, tag);
            }
        }
        toastr.success('Updated');
        close();
    }

**Comment by diurvan** [comment]
Hi Nikinoodle.
I need your help for a project that starts soon. Please contact me to diurvan1@gmail.com or by Skype as "diurvan". Thanks

**Comment by almorax** [comment]
Also I want to change post's date because I imported posts, they are all incorrect.
