### ISSUE TITLE
Which branch is used to contribute?

### ISSUE THREAD

**Issue by phucthaidoan** [blogifierdotnet/Blogifier#298]
I am trying to find the information on how to contribute code-based, but not sure which branch is used to contribute now 😄 .

`Code in the main branch is under development` => Using `main `branch is fine, or `dev `branch?

Thanks,

**Comment by rxtur** [comment]
Right now main and dev are in sync. It is preferable to use dev branch for pull requests, simply because we can pull to local, verify all is good and only then update main branch.
