### ISSUE TITLE
Windows Error Log IIS Event ID 1020 - AspNetCore Module V2 - framework not found

### ISSUE THREAD

**Issue by TVBanks98** [blogifierdotnet/Blogifier#305]
**Describe the bug**
I installed Blogifier today along with Dot Net Core v6.  My site throws the following error in the Windows Event Log for each visit and throws an "HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure" error page.  

```
Level: Error
Event ID: 1929
Source: IIS AspNetCore Module V2
Event Details: Application '/LM/W3SVC/99/ROOT' with physical root 'X:\Inetpub\blog.xxxxxxxxxxxxxx.com\' failed to start process with commandline 'dotnet .\App.dll' with multiple retries. Failed to bind to port '39644'. First 30KB characters of captured stdout and stderr logs from multiple retries:
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '2.2.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=2.2.0&arch=x64&rid=win10-x64
```

System requirements for Blogifier are listed as "Dot Net Code v5 for higher".  The (apparently) requested version 2.2 is long out of support.  

**Screenshots**

**Additional context**

I installed the [ASP.NET Core Module/Hosting Bundle](https://dotnet.microsoft.com/permalink/dotnetcore-current-windows-runtime-bundle-installer) using the link referenced in [this article](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0).

**Comment by rxtur** [comment]
Has been updated to use .net 6.0
