### ISSUE TITLE
Questions: How the data validation works for Blogifier

### ISSUE THREAD

**Issue by LinQiaoPorco** [blogifierdotnet/Blogifier#306]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/76023599/148148398-d3a52e6e-f887-4e1c-865f-74f84690c435.png">

Does the floating data validation message come from standard ASP.NET Core Blazor data binding and validation function?
It seems different with the standard red text validation message:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/76023599/148149286-b7fc7097-f3aa-469c-916f-1b952a359bec.png">

I tried to switch Blogifier from local sign-in to OpenID Connect sign-in, but I found the profileview.razor in Blogifier.Admin reported that the data validation failed, because the OnInvalidSubmit was triggered:

`<EditForm Model="@Author" OnValidSubmit="SaveProfile" OnInvalidSubmit="ShowErrorSummary">`
and
`protected void ShowErrorSummary()
{
        displayValidationErrorMessages = true;
    }`

but no error message printed out by `<ValidationSummary />`  as:
`@if (displayValidationErrorMessages)
    {
        <div class="col-md-4" style="margin-top:10px">
            <label>Validation Messages: </label>
            <ValidationSummary />
        </div>
    }`

**Comment by rxtur** [comment]
I believe popup in your screenshot coming from standard HTML control validation driven by input type set to "email"

```html
<input class="form-control" type="email" @bind="Author.Email" />
```
