### ISSUE TITLE
What tools were used to compile static files in Blogifier?

### ISSUE THREAD

**Issue by LinQiaoPorco** [blogifierdotnet/Blogifier#311]
Hi,

Except `npm`, what tools were used to compile static files into wwwroot/themes?
Gulp or something else?
I would like to keep the same routine with your repo.
It would be fantastic to have a manual or intro added to README.md for better understanding.

Thanks!

**Comment by david-randoll** [comment]
I think it is just the dotnet publish command. You can learn more about it on Microsoft site:

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish

**Comment by LinQiaoPorco** [comment]
> I think it is just the dotnet publish command. You can learn more about it on Microsoft site:
> 
> https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish

Thanks!
