### ISSUE TITLE
Stored XSS via filename parameter in '/api/storage/upload/PostImage'

### ISSUE THREAD

**Issue by tuando243** [blogifierdotnet/Blogifier#316]
**Describe the bug**
Stored XSS exists in  Blogifier 3.0 via filename parameter in '/api/storage/upload/PostImage'.

**Steps to reproduce**

1. Login as admin.
2. Click on 'New post'.
3. Click on 'Insert Image' and  insert the following payload `<img src=1 onerror=alert(1)>` in filename field. 
4. Click on Save, Publish and View the post.

![1](https://user-images.githubusercontent.com/35623498/177812370-004d0730-cbbc-43dd-bcdb-c23bcbd545fe.PNG)

![2](https://user-images.githubusercontent.com/35623498/177812655-49e34e9b-91b9-44b3-ae13-ee8596d2a52d.PNG)

![3](https://user-images.githubusercontent.com/35623498/177812753-8d164252-b7e3-448e-adfe-350fb8212b3a.PNG)

**Comment by rxtur** [comment]
Fixed with commit 97fcdac
