### ISSUE TITLE
Stored XSS on upload files.

### ISSUE THREAD

**Issue by tuando243** [blogifierdotnet/Blogifier#317]
**Describe the bug**
The web application allows image upload and attacker was able to upload a file containing HTML content. XSS payload can be injected in the file uploaded.

**Steps to reproduce**

1. Login as admin.
2. Click on 'New post'.
3. Click on 'Insert Image' and upload .html file with xss payload inside.
4. View the file with path in response.

![1](https://user-images.githubusercontent.com/35623498/177819110-bbb0b16f-bae8-41a7-907d-b46d765c4e39.PNG)

![2](https://user-images.githubusercontent.com/35623498/177819141-32414a4e-b05a-47aa-bd63-27d25fc4d00c.PNG)

![3](https://user-images.githubusercontent.com/35623498/177819155-4f802268-0705-4d4f-93ba-2bce30762ed0.PNG)

**Comment by rxtur** [comment]
Fixed with commit 97fcdac

**Comment by rxtur** [comment]
Fixed with commit 97fcdac
