### ISSUE TITLE
there is something with "Resource.zh-CN.resx" that I can't understand?

### ISSUE THREAD

**Issue by stilltooyoung** [blogifierdotnet/Blogifier#322]
When I use visual studio to build,everything is OK.
But when I use "dotnet build","Resource.zh-CN.resx" doesn't work.There is no directory named "zh-CN" under the directory "src\Blogifier.Shared\bin\Debug\net6.0\":
![image](https://user-images.githubusercontent.com/22746567/193437146-20809295-49cd-4163-8454-f5e979ac4274.png)
Can someone help with this?appreciate!

**Comment by rxtur** [comment]
This is odd, I don't see any issues removing debug folder and re-generating resource folders, including zh-CN:

![explorer_tMHM3H77uF](https://user-images.githubusercontent.com/1932785/197361908-4d233adb-e63a-4d10-afbf-38aa7f8204a0.png)

**Comment by dorthl** [comment]
@stilltooyoung  This problem should no longer exist
