### ISSUE TITLE
该项目是否仍在维护？

### ISSUE THREAD

**Issue by weiai-weiai** [blogifierdotnet/Blogifier#323]
我下载并尝试使用该项目，我发现该项目仍然有优化空间，请问该项目是否仍在继续优化

**Comment by dorthl** [comment]
@weiai-weiai  现在已经开始升级到.net 7 , 具体可查看dev 分支

**Comment by bicijinlian** [comment]
官网错误啊
![image](https://github.com/blogifierdotnet/Blogifier/assets/10394955/67fe8b5f-3a09-4a25-999d-4752d6bb2087)

**Comment by dorthl** [comment]
原始仓库的持有者不太能联系上 这个域名不知道是谁持有者。我问问 如果可能的话我会部署一个示例
