### ISSUE TITLE
Changing DB to SQL Server in VS does not work as described in 02-Database.md

### ISSUE THREAD

**Issue by planserver-pro** [blogifierdotnet/Blogifier#324]
I try to change the DB provider to SQL Server as described in 02-Database.md. However, when running the 
`Add-Migration Init -o Data\Migrations `
command, I get this error in Paket Manager Console:
`Could not load assembly 'Blogifier'. Ensure it is referenced by the startup project 'Blogifier.Core'.`
Trying to add this reference is denied by VS because this would cause a ring reference. 
This happens with both v3 and the current dev branch.
Any suggestions?

**Comment by rxtur** [comment]
Not sure what you doing differently, probably setting Core as "startup" instead of "default" in the PM console: 

![devenv_Gb3sk3a5o3](https://user-images.githubusercontent.com/1932785/197361268-e05db533-7d90-4f2b-a5f3-b33dbf39ec63.png)

**Comment by planserver-pro** [comment]
Thanks for that quick help, rxtur!
