### ISSUE TITLE
I think it's time to upgrade to .NET 7 :) 

### ISSUE THREAD

**Issue by ravichigurupalli** [blogifierdotnet/Blogifier#328]
with .NET 7...It's entirely native, with no IL or JIT, and provides fast startup time and a small, self-contained deployment.

I am interested to contribute, Please accept my request.

**Comment by dorthl** [comment]
@ravichigurupalli  
The.net 7 upgrade is underway in the dev branch and features are still being refined
There are problems with file storage and database migration. At present, only mysql is tested, and it is necessary to consider how to implement migration of multiple databases with the same release version.
It's all in the works looking forward to your sharing

**Comment by ravichigurupalli** [comment]
got it. Thanks for the response.
