### ISSUE TITLE
Mime types on scripts and css

### ISSUE THREAD

**Issue by Nikkinoodl** [blogifierdotnet/Blogifier#33]
Was unable to implement application options to prevent sniffing files and overriding the Content-Type header when using the standard admin Views because mime types are not set for the css and script content.

As a workaround I used a custom version of the admin app and added type="text/css" and type="text/javascript" tags where needed.

Should  blogifier.core have these set by default?

Simon

**Comment by rxtur** [comment]
That no longer relevant with all the latest changes.
