### ISSUE TITLE
Lots of .Result usages in awaitable methods

### ISSUE THREAD

**Issue by dustinhorne** [blogifierdotnet/Blogifier#35]
Looking at the code and finding lots of .Result usages when calling methods that return Task.  This should be changed to avoid potential deadlock issues.  These should be awaited and the controller actions be modified to be async and return Task<..model..>.

**Comment by pablotdv** [comment]
I changed all possible methods to use async/await 
See the PR https://github.com/blogifierdotnet/Blogifier/pull/82

**Comment by rxtur** [comment]
Actually had to revert it: I'm ok with async/await updates, but there were lots of other changes including switch to SQL Server provider. Under SQLite, I got errors and things like widgets stopped working. In general, it is better to isolate pull requests into single digestible tasks so they can be reviewed and tested more easily.
