### ISSUE TITLE
Move from BlogEngine to Blogifier

### ISSUE THREAD

**Issue by ugochirico** [blogifierdotnet/Blogifier#37]
Hi, I have a blog with BlogEngine 3.5.0 and I want to move it to Blogifier.
Do you have any script or suggestion to do that?

**Comment by rxtur** [comment]
Get RSS feed of your blog, for example: "http://rtur.net/blog/syndication.axd?maxitems=1000".
Save it as c:\blog.xml
Import posts: settings -> import RSS and give "c:\blog.xml" as rss url.

The "domain" in this example would be "http://rtur.net/blog" and is optional, helps to resolve relative paths in some edge cases. And you can point "rss url" directly to your feed but for large blogs download option is more reliable.

**Comment by ugochirico** [comment]
Many thanks. I'll try
