### ISSUE TITLE
Improve the description of Blogifier

### ISSUE THREAD

**Issue by awulkan** [blogifierdotnet/Blogifier#39]
I tried to get some feedback of what people thought of this project and I was mainly met with responses like "I don't even understand what it is/does". Maybe it would be a good idea to explain a bit more in depth about what Blogifier is and why people should use it. Simply saying that it "blogifies" ASP.NET sites doesn't really explain much about it.

I really think this project looks interesting and I look forward to seeing it grow. :)

**Comment by rxtur** [comment]
Maybe not perfect, but updated and hopefully an improvement.

**Comment by awulkan** [comment]
I don't see any changes. Or are you saying that it doesn't require any?

**Comment by rxtur** [comment]
Description was changed for a package (https://www.nuget.org/packages/Blogifier.Core). The "Core" is actually just a back-end for the application we building. More on this here: http://www.rtur.net/blog/post/2017/09/25/the-failure-of-communication
