### ISSUE TITLE
tinymce editor settings

### ISSUE THREAD

**Issue by murst** [blogifierdotnet/Blogifier#40]
It would be helpful if we had more control of the HTML that can go inside the tinymce editor. I was recently attempting to format the posts I imported from BlogEngine, and noticed that by default I cannot add my own SCRIPT or STYLE tags.

I fixed this by adding the following to tinymce.init() in editorController.js:

`extended_valid_elements: '+*[*]',
valid_children: '+body[style]',`

**Comment by rxtur** [comment]
Moved to Markdown.
