### ISSUE TITLE
Feature Request -> manual post priority

### ISSUE THREAD

**Issue by murst** [blogifierdotnet/Blogifier#41]
It would be really nice if we had a way of forcing certain posts to appear first on the blog. Certain articles on my blog are much more popular than others, and I'd like them to appear on the home page, even though they are older posts.

A priority field could be added to posts (with a default priority of 0). All posts could be sorted by descending priority, followed by descending date.

**Comment by rxtur** [comment]
There will be "featured posts" that should cover it. Not in the coming release but in the next down the road.
