### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by ugochirico** [blogifierdotnet/Blogifier#42]
I have to use MySQL instead of SQLServer or Postgres. 
Does Blogifier support MySQL?
If not how can I do that?

**Comment by rxtur** [comment]
Current 1.1 only supports SQL Server and PostgreSql.

In the coming 1.2 release it should work with any Entity Framework provider, including MySql.

**Comment by ugochirico** [comment]
ok. When do you think the version 1.2 will be ready?

**Comment by rxtur** [comment]
In a week or two.

**Comment by rxtur** [comment]
The 1.2 release should support MySql provider among others, let me know if you'll see any issues.
