### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by murst** [blogifierdotnet/Blogifier#43]
I know you guys are trying to finish up v1.2, but here's some suggestions for features/updated for 1.3 (or whatever version will be next):

- Single Blog features are currently missing. There's no way to set/get the custom fields & get posts by category when in Single Blog mode. Perhaps the way to address that is to make the "admin" (or first) profile the default profile if no other profile is chosen?

- Create a setting for "AdminRoute" that is equivalent to "BlogRoute" so that we can customize the blog admin path.

- Add a (tinymce) field to "Profile" settings so that authors can write up a description for themselves. Then, clicking on the name of the author on a post (for example) could take you to their public profile page which talks about the author. From there, you could view their posts, etc.

- Featured posts support

I've slowly been making progress on creating [my own theme for Blogifier](https://bloodforge.com/). There are still some public APIs that I needed to create to make this happen. Some of them are meant to address the points I raised above. I have a github repo for my theme.  If you're interested in which APIs I needed to add (in case you want to add something similar to Blogifier), you can find them at [https://github.com/murst/Blogifier-Angular-Material](https://github.com/murst/Blogifier-Angular-Material)

**Comment by rxtur** [comment]
Awesome, I"m keeping an eye on all the suggestions here, even if not answered directly they all carefully considered.

**Comment by Nikkinoodl** [comment]
Can I also add to this list a method on either the public or private API that can be called for Sitemap generation by the parent app. All the current methods use paging.

**Comment by murst** [comment]
@Nikkinoodl,

You can actually do that already. I have a sitemap in my WebApp project. You can see how I'm getting those posts and adapt it to your website:

[Source: SitemapController](https://github.com/murst/Blogifier-Angular-Material/blob/master/src/Controllers/Api/Public/SitemapController.cs)
[Example XML Sitemap](https://bloodforge.com/sitemap.xml)

**Comment by Nikkinoodl** [comment]
Thanks Murst.  I've done something similar already with my own website app, but it's less elegant than your solution.  Thanks!

**Comment by farzindev** [comment]
Also if you see any problem with the UI on any device let me know. We are going to release 1.2 next week.

CC: @murst, @Nikkinoodl

**Comment by Nikkinoodl** [comment]
Hey Francis - I've got 1.2.2 up and running. It looks great and is very stable. In terms of UI the only changes I made to the Admin app were to include some extra features in the TinyMCE toobar and context menus:
Toolbar: undo, redo, indent and outdent  - these make the editor easier to use
Context menu: image - this gives the ability to easily add 'alt' text and resize any images.

Thanks!
Simon

**Comment by rxtur** [comment]
Closing due to most discussed no longer relevant and can be misleading.
