### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by alexandrudanpop** [blogifierdotnet/Blogifier#46]
Would be nice to have some kind of automated build & unit test runner for each commit.
Orchard for example uses Travis Ci and Appveyor: https://ci.appveyor.com/project/alexbocharov/orchard2/branch/master

I can help setting up Appveyor (free to use for Open Source projects). I will set the appveyour Yaml file in my fork of Blogifier.Core and submit a PR. 

Then you can go to https://ci.appveyor.com/signup and chose Free - for open source projects and set it up, it will hook to your github account and do continuos builds and run tests depending on the yaml config for each commit.

**Comment by rxtur** [comment]
We actually do have continues integration on every commit to master branch, it is just not included into source code repository. Because this integration also deploys to Azure demo site (blogifier.azurewebsites.net) and publishes to Nuget.org.

**Comment by alexandrudanpop** [comment]
That's great. I personally think it's nice to see all commits being built / tested, especially on active branch (dev).

**Comment by rxtur** [comment]
Using CI to Azure (blogifier.azurewebsites.net).
