### ISSUE TITLE
Conflicting category slugs

### ISSUE THREAD

**Issue by rxtur** [blogifierdotnet/Blogifier#5]
When different authors create category with same name they conflict with each other. Make category slug unique by adding counter or use author/category combination.

**Comment by farzindev** [comment]
or maybe we should share the category for all authors.
If someone creates a category we could show that for everyone. if they are writing on the same blog, so then it's not good to have multiple categories but the same category content. then visitors will be confused.

**Comment by rxtur** [comment]
The categories completely reworked and now belong to authors rather than been shared. So whenever you click on category it brings you to author's page and category identified by both author and category slugs, so there should be no conflicts.
