### ISSUE TITLE
Razor pages

### ISSUE THREAD

**Issue by senadburak** [blogifierdotnet/Blogifier#54]
Problem with routing in case of integrating Blogifier.Core to an ASP.NET Core project with Razor pages.

The error we get is:
RouteCreationException: The following errors occurred with attribute routing information
For action: 'Blogifier.Core.Controllers.AdminController.Index (Blogifier.Core)'
Error: The attribute route 'admin/{page:int?}' cannot contain a parameter named '{page}'. Use '[page]' in the route template to insert the value ''
etc.
Regards, Senad

**Comment by rxtur** [comment]
You need to add MVC to your project, Blogifier uses MVC for routing but we can't handle it inside Core because it can clash with routes registered in parent application. I don't think it will effect your existing Razor pages in any way, they should work fine side by side.

**Comment by senadburak** [comment]
Thank you for the quick response.
However, it still doesn't work. Please try it yourself, ie. create a new ASP.NET Core 2.0 application with Razor Pages, modify Startup.cs as you suggested and run. No go.
I believe Blogifier.Core has to be modify if we wish (as I do) to be compatible with the Razor Pages. The problem is I don't have an idea where to start.

**Comment by rxtur** [comment]
Yeah I see what you saying, apparently "page" is a reserved word for Razor to handle attributes. We'll need to fix it, probably move to query string like "?page=2" instead of "/page/2".

**Comment by senadburak** [comment]
Excellent, looking forward to see a fix soon.
Razor pages is excellent technology and more and more people will use them in the future. With the early adoption to the .net standards of relatively new solution as Blogifier is, it will be a big plus. Thanks again.

**Comment by rxtur** [comment]
Should work fine with latest (1.2.2) release.

**Comment by senadburak** [comment]
rxtur,
thankyou very much for the update. It works like a charm.
