### ISSUE TITLE
Post cover on imported blogs mixed up

### ISSUE THREAD

**Issue by alexandrudanpop** [blogifierdotnet/Blogifier#57]
1. Import posts from a BlogEngine blog using Import RSS function, including images (I used http://www.control-f5.com/syndication.axd in my import):
![image](https://user-images.githubusercontent.com/15979292/31098121-459c7214-a7ca-11e7-908f-9a1fc424a70f.png)

2. Set the cover on the first imported **post** using imported image1.
3. Set the cover on the second imported **post** using imported image2.

Then after you go to the first post to view it again it's cover is changed from the one you first set. Tried it on
http://blogifier.azurewebsites.net/blog/alex0808
With user & pass: 
testAdmin1@test.com

**Comment by rxtur** [comment]
When you saying "first imported blog" - do you mean "first imported post"? Trying to avoid confusion between the two, they mean very different things. So we talking about blog cover or post cover?

**Comment by alexandrudanpop** [comment]
Sorry for that, I updated my first comment to make things more clear.

**Comment by rxtur** [comment]
So I did at demo site for your account:
1. Go to post 1 and set cover to "react".
2. Go to post 2 and set cover to "nlog".
3. Went back to post 1 expecting cover to change.

It didn't change, cover stay as it was set in step 1. Am I completely misunderstanding this issue? Can you consistently reproduce it?

**Comment by alexandrudanpop** [comment]
Video: https://youtu.be/-qpjj8MLGv4

**Comment by rxtur** [comment]
Oh I see, there are issues importing images in the blob format, I'll take care of it.

**Comment by rxtur** [comment]
This should work after [latest commit](https://github.com/blogifierdotnet/Blogifier.Core/commit/85a1384570b101a59ae7d60769fa79d9b3dc9929).
