### ISSUE TITLE
Featured Posts Migration

### ISSUE THREAD

**Issue by Nikkinoodl** [blogifierdotnet/Blogifier#59]
To get version 1.3 up and running you'll need to apply database migrations in order to add new columns to the Blogifier tables. You may find this useful if you're struggling with the commands.

My project structure is:

-PBSB_Core (startup project which depends on Blogifier.Core)
-Blogifier.Core

This is the PowerShell command I ended up using in order to apply the FeaturedPosts migration to the development database:

`Update-Database -Migration FeaturedPosts -Project Blogifier.Core -StartupProject PBSB_Core -Context BlogifierDbContext`

Cheers,
Simon

**Comment by rxtur** [comment]
You actually should be prompted to run migration by clicking a button when get to website first time after upgrade. May not work for some reason in your case.

**Comment by Nikkinoodl** [comment]
I'm certain that it's my fault, but I couldn't figure it out.

It's not a big deal - I just wanted to make sure that there was a searchable workaround out there in case anyone else ran into problems.
