### ISSUE TITLE
Compiler Error in Production

### ISSUE THREAD

**Issue by Nikkinoodl** [blogifierdotnet/Blogifier#63]
I'm getting this error in my Production environment when I try to load the Admin app (it doesn't occur in my Development environment).  Any thoughts?

Assembly 'Blogifier.Core' with identity 'Blogifier.Core, Version=1.4.5.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by rxtur** [comment]
Your local framework (System.Runtime, Version) is at 4.2 and remote uses 4.1. 
You need to sync /refs folder on prod to use same version you have locally.

**Comment by Nikkinoodl** [comment]
Rxtur - thanks for pointing me in the right direction.  I had to explicitly include the MvcRazor reference assemblies in the publish for my main application. Including the additional line in my csproj file fixed the problem.

`  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
  </PropertyGroup>`
