### ISSUE TITLE
Exception after using mysql 

### ISSUE THREAD

**Issue by liuyl1992** [blogifierdotnet/Blogifier#64]
Exception :Message	"An item with the same key has already been added. Key: Microsoft.EntityFrameworkCore.Infrastructure.Internal.MySqlOptionsExtension"	string

Startup:
![image](https://user-images.githubusercontent.com/16396828/33240748-11afb144-d2f6-11e7-8203-932205c565da.png)

![image](https://user-images.githubusercontent.com/16396828/33241932-c68afdd8-d307-11e7-9789-a6837d15f441.png)

**Comment by liuyl1992** [comment]
it is normal after  using sqlserver 
![image](https://user-images.githubusercontent.com/16396828/33246493-eb550850-d34f-11e7-97ba-451d79404e6a.png)
![image](https://user-images.githubusercontent.com/16396828/33246500-0175af72-d350-11e7-9971-baf3ab0f4c1a.png)
My mysql provider is  "Pomelo.EntityFrameworkCore.MySql" Version="2.0.0-rtm-10062"

BUT

be broken after route /admin
![image](https://user-images.githubusercontent.com/16396828/33247679-fb491052-d35a-11e7-9917-a4265789c582.png)

**Comment by vivekse** [comment]
@liuyl1992 Any workaround for this issue? I am also kind of stuck at the same issue.

**Comment by rxtur** [comment]
Can only support SQLite and SQL Server. Making work with every provider is just not possible.
