### ISSUE TITLE
 This does not need to take the initiative to migrate it?

### ISSUE THREAD

**Issue by liuyl1992** [blogifierdotnet/Blogifier#65]
This does not need to take the initiative to migrate it?

BlogifierDbContext auto migration?

**Comment by rxtur** [comment]
Current code in dev branch is set to run without database (it is ignored in git).

So in appsettings.json we got: "InitializeDatabase": true

This should create new database and run migrations to created data tables.

Once database created, it can be set to false to suppress initialization check.
