### ISSUE TITLE
 An error occurred when release mode 

### ISSUE THREAD

**Issue by liuyl1992** [blogifierdotnet/Blogifier#66]
it just happens in the release mode,debug is normal
![image](https://user-images.githubusercontent.com/16396828/33260382-9db9af7e-d39a-11e7-89a3-334c14909da3.png)

**Comment by rxtur** [comment]
Not able to recreate.

**Comment by leofoe** [comment]
I had the same error. The problem is in the location of the database. In development the Data-directory is in the wwwroot folder. In production it is under the rootdirectory of the app.
