### ISSUE TITLE
it is broken out after release to Linux

### ISSUE THREAD

**Issue by liuyl1992** [blogifierdotnet/Blogifier#67]
it is broken out after release to Linux,but it is Passed on windows,I think the reason is that Windows and Linux have different paths, do you think?
Exception:
[Error] The view '"~/Views/Blogifier/Themes/Standard/Index.cshtml"' was not found. Searched locations: ["~/Views/Blogifier/Themes/Standard/Index.cshtml"]

**Comment by rxtur** [comment]
I think its an issue with deployment - you must have all publishing files, including "Blogifier.Web.PrecompiledViews.dll" etc. and have "refs" folder with framework specific files.

(this is for dev branch files, if you use master I believe it should be "WebApp.PrecompiledViews.dll" or something like this)

**Comment by liuyl1992** [comment]
but I execute the dotnet .dll command in the publish file, everything works, but put the publish file on iis or linux jexus, the site is up and running, but some pages get an exception: "Views/XXX/xxx.cshtml" was not found

**Comment by liuyl1992** [comment]
some picture:
![image](https://user-images.githubusercontent.com/16396828/33474074-f3c6856a-d6b3-11e7-9591-d5d995ac4719.png)
![image](https://user-images.githubusercontent.com/16396828/33474120-1eb2ed90-d6b4-11e7-9258-f258585ffa6a.png)

Only this can not be found ~/Views/Blogifier/Themes/Standard/Index.cshtml,other is normal

**Comment by rxtur** [comment]
Here is running on Ubuntu in VS Code. I'll check out publishing this weekend, but running in VS does not give me any errors.

![img](https://pbs.twimg.com/media/DP7Z6zoXkAIZ7gl.jpg)

**Comment by rxtur** [comment]
I'm running it on IIS all the time - do you have [IIS configured to run .net core](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x) apps? Can you run on your IIS any .net core web app?

**Comment by liuyl1992** [comment]
I publish Blogifier to run on IIS, everything is normal and all views can also be found,but CentOS is broken out and visual studio default asp.net core template project is normal on CentOS

**Comment by rxtur** [comment]
Unfortunately, we can't test every Linux distro out there, so there might be edge cases that we'll not able to cover.
