### ISSUE TITLE
Fix PostBuild Task

### ISSUE THREAD

**Issue by dansiegel** [blogifierdotnet/Blogifier#69]
Executing xbuild requires that the build host has xbuild available during the build otherwise the entire build will fail. This is easily overcome by using the MSBuild Copy Task.

I already have the fix for this and making the API more intuitive:

```cs
services.AddBlogifier(databaseOptions, Configuration);
app.UseBlogifier(env);
// instead of
Configuration.InitServices(services, databaseOptions, Configuration);
Configuration.InitApplication(app, env);
```

I'm happy to submit a PR, just need to know if you want the PR based on Dev or Master

**Comment by rxtur** [comment]
Not a big difference as they in sync right now, but dev would be better.
