### ISSUE TITLE
Editor improvement

### ISSUE THREAD

**Issue by farzindev** [blogifierdotnet/Blogifier#7]
I think it would be much better if we open a new tab and show the post when we click on the publish button.

**Comment by rxtur** [comment]
The JavaScript is restricted in this situation, for security reasons - to prevent pop-ups. There are workarounds, but they ugly and don't always work - blockers will prevent them, user preferences can disallow etc. 

We can add link to the post when it published in the editor page as alternative.

**Comment by farzindev** [comment]
Yeah, the link to the post would be great.

**Comment by rxtur** [comment]
The "view" button added in the editor for published posts next to "save".
