### ISSUE TITLE
Custom Template Documentation

### ISSUE THREAD

**Issue by dansiegel** [blogifierdotnet/Blogifier#71]
When you get a chance, having an entry in the Wiki for how to add your own custom themes would be awesome.

**Comment by ugochirico** [comment]
Hi agree with @dansiegel. Can you add an entry in the wiki about  how to create a custom theme?

**Comment by rxtur** [comment]
Documentation added with some basic examples, more on the way.
https://github.com/blogifierdotnet/Blogifier/blob/master/docs/CustomThemes.md
