### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by dansiegel** [blogifierdotnet/Blogifier#72]
I really like where Blogifier is going, and I realize that it's still a relatively new codebase, but there are a few features I wasn't really seeing mentioned here, but would really like:

1. Custom Pages - most blogs generally also have some custom pages. These could be an "About Me", a "Resume", etc.
1. Contact Page - again many websites generally want to enable users to contact the site owner. Certainly a v1 could be a simple contact form, but it would be awesome to have a form builder so that forms could be used across one or more pages.

**Comment by dansiegel** [comment]
Also not sure if it's a limitation of the default template or framework limitation, but I was noticing there's no way to set the url or enable/disable the social links

**Comment by rxtur** [comment]
We've just added widgets framework and now working on themes framework, which will allow theme customization, external loading and so on. Form builder is something we can look into later, but its not high on priority list to be honest, at least right now.

**Comment by dansiegel** [comment]
Totally understandable. Also forgot to mention Blog Comments. I know that there is a wiki entry for Disqus but having it as a built in feature would be nicer.

**Comment by firatesmer** [comment]
- Let us change the post's date because I imported posts and they are all incorrect.
- Maybe seperation between post's cover and thumbnail images (main page) and not just png?
- Folder creation in upload

**Comment by Gaetan-dc** [comment]
Have the ability to display the full post in a post list, instead of just the excerpt. The data isn't even accessible in the view as it is right now so I can't get away with a theme.

**Comment by flashvenom** [comment]
I am going to be slapping on a jquery datepicker to the date published field in admin. I really like the simple look & feel of this one: https://www.jqueryscript.net/time-clock/Super-Tiny-jQuery-HTML5-Date-Picker-Plugin.html  I think it matches blogifier's UI aesthetic.
Would you like me to push my changeset after I implement?

**Comment by rxtur** [comment]
> I am going to be slapping on a jquery datepicker to the date published field in admin. I really like the simple look & feel of this one: https://www.jqueryscript.net/time-clock/Super-Tiny-jQuery-HTML5-Date-Picker-Plugin.html I think it matches blogifier's UI aesthetic.
> Would you like me to push my changeset after I implement?

I think you would need datetime picker. Anyway, if you do something that can be useful to others, just submit pull request for review.

**Comment by Chainerenator** [comment]
Would be nice to include also custom code to header and some trackers too!

**Comment by gkaya** [comment]
I would definitely vote for "comments" module, should relatively easy to add.

I think custom forms and other pages can be handled with static files easily.

**Comment by rxtur** [comment]
Closing to avoid confusion, most of this pretty old and no longer relevant.
