### ISSUE TITLE
About Widgets

### ISSUE THREAD

**Issue by marcuxyz** [blogifierdotnet/Blogifier#74]
does not work after following the tutorial:
https://github.com/blogifierdotnet/Blogifier/wiki/Widgets

Not show in .../OneFour/index.cshtml

I did not have time to look at the implementation, but as soon as I got home from work I will look.

**Comment by n-develop** [comment]
Have you tried setting "OneFour" as your selected theme?

![image](https://user-images.githubusercontent.com/13137880/34126017-7cbd2e78-e438-11e7-8894-40eaca382271.png)
