### ISSUE TITLE
I have no idea about newsletter in admin dashboard.

### ISSUE THREAD

**Issue by forconz** [blogifierdotnet/Blogifier#75]
How to manage newsletter in admin dashboard?

**Comment by rxtur** [comment]
When someone subscribes to newsletter, new email added to the list.
In the admin, click "Packages" and then click "Newsletter". It should load list of subscribers. When you publish new post, subscribers get email notification.

 Currently, you can only view this list and remove emails from the list. But there will be template edit and other improvements coming soon.

**Comment by forconz** [comment]
In the admin, click "Packages" and then click "Newsletter". It should load list of subscribers. 
the admin path is following below:
/blogifier/widgets/Newsletter/settings

It is ok, I saw the subscribers, and I can emails from the list.

many thanks.
