### ISSUE TITLE
Revert my changes

### ISSUE THREAD

**Issue by pablotdv** [blogifierdotnet/Blogifier#84]
Why did you reverse my changes?https://github.com/blogifierdotnet/Blogifier/commit/0dac10c7164b29a21f7978792c002f704e2a2251

Why do not you use async/await?

**Comment by rxtur** [comment]
> Actually had to revert it: I'm ok with async/await updates, but there were lots of other changes including switch to SQL Server provider. Under SQLite, I got errors and things like widgets stopped working. In general, it is better to isolate pull requests into single digestible tasks so they can be reviewed and tested more easily.

https://github.com/blogifierdotnet/Blogifier/issues/35

**Comment by pablotdv** [comment]
I will work on more tests on these changes and create the PR again.

**Comment by rxtur** [comment]
That would be great, just keep in mind that I need to review and test every pull and if there too many changes, some unrelated to description, it is very hard to guarantee nothing was broken. Better approach would be have single pull for single functionality, so they can be rolled in or reverted individually. I really appreciate you've done tone of work there, but I need to keep code stable.

**Comment by pablotdv** [comment]
Alright man, I will change to baby steps each pull request. 
Let's go by parts. As Jack the Ripper would say.
