### ISSUE TITLE
Unable to create a new user

### ISSUE THREAD

**Issue by ugochirico** [blogifierdotnet/Blogifier#86]
I've just installed the version 1.5 on my IIS 7 under windows Server 2008 R2 Enterprise.
All seems to work except the creation of a new user.
When I try to add a new user, by typing email, full name and password I got a blank page with this url:
http://xxxxxx.com/Admin/Register?returnUrl=~%2Fadmin%2Fsettings%2Fusers
and no new user has been created.

How can I create a new user?

**Comment by rxtur** [comment]
Try to turn off eTag middleware as described [here](https://github.com/blogifierdotnet/Blogifier/issues/85). This should display error instead of blank page, looks like etagger suppresses it, I'm going to fix it.
