### ISSUE TITLE
RSS Import doesn't work

### ISSUE THREAD

**Issue by ugochirico** [blogifierdotnet/Blogifier#87]
I've just installed version 1.5. I download the zip release and installed on my Windows Server 2008 R2 Enterprise with ISS.
I changes the appsettings to create a new database and I create a new user in the login section.

I tried to import the RSS from my BlogEngine blog but I got "Failed" red notification at bottom right without any other indication.
I tried to import it in several ways: by saving locally the rss (as described in the wiki), by not setting "import images" and "import attachments", by not giving any domain url but nothing. I still get "failed"

I tried to set the loglevel to "Debug" to try to understand but in the log I cannot see any error.

Is this a bug or is there something else that I have to do to import the RSS?

**Comment by rxtur** [comment]
Did you try different RSS feed? For example, from wiki: http://rtur.net/blog/syndication.axd
If that works but your RSS still fails with no errors in log, it means something in your RSS that not expected. If its publicly available, post URL and I can check this out.

**Comment by ugochirico** [comment]
I get the same error with your rss: http://rtur.net/blog/syndication.axd
"failed" with no other messages

my rss is http://ugochirico.com/syndication.axd

**Comment by rxtur** [comment]
I did fresh clone from repo and have no problem importing your rss. My guess would be that your server is running in different locale and things like date format could be an issue - when I import your feed it works but misses published date and my feed brings all dates correctly. I'll look into date formats in import.

Update:
to fix date, I had to make this change in the Blogifier.Core.Common.SystemClock

from: result = DateTime.ParseExact(date, str, DateTimeFormatInfo.InvariantInfo);
to: result = DateTime.ParseExact(date, str, new CultureInfo("it-IT"));

Try and see if this fixes it for you.

![rsstest](https://user-images.githubusercontent.com/1932785/34616149-e0b80d68-f1fc-11e7-9661-4f01ba955a8f.PNG)

**Comment by Nikkinoodl** [comment]
I had a problem with this when I first tried it.  I documented the fix in issue #28 

WebDAV was installed on the server and was causing errors even though it was not enabled. After removing WebDAV in the server manager, everything worked.

**Comment by rxtur** [comment]
RSS import in latest release much reworked (and still improving), don't think this issue still relevant.
