### ISSUE TITLE
Prod Issue

### ISSUE THREAD

**Issue by firatesmer** [blogifierdotnet/Blogifier#88]
Hello,

I just published blogifier to my host but I got an error.

I contacted my host company and they say it's not their fault, it's about software. I have no db or any other specific setting. (default settings)

Edit : Actually they say my web.config file didn't optimized correctly. (?)

Also I gave write permissions. Still no luck. Can you help me? Thanks.

this is my web.config file

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\Blogifier.Web.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
<!--ProjectGuid: 61f3cc98-a01e-44d4-9e5e-4099274cccb6-->
```

+

```
{
  "ConnectionStrings": {
    "DefaultConnection": "DataSource=Data\\app.db"
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "Blogifier": {
    "BlogRoute": "",
    "InitializeDatabase": true,
    "BlogAdminFolder": "Views/Blogifier/Admin",
    "ProfileAvatar": "/admin/img/avatar.png",
    "Demo": "false",
    "BlogStorageFolder": "data"
  }
}
```

![image](https://user-images.githubusercontent.com/15785611/34641668-8efa5036-f318-11e7-8ffa-c235a2f67648.png)

**Comment by rxtur** [comment]
Does your host supports .net 2.0? You can try to deploy simplest possible asp.net core app from VS template to make sure it works and, if it does, compare config files etc.

**Comment by firatesmer** [comment]
Well, I did as you say and still no luck. They say "they have nothing to do" same as me. I'm gonna change my hosting company. Thanks for help.

**Comment by leofoe** [comment]
Look at the logfiles. 
I had this error and the problem was "Unable to open database".
