### ISSUE TITLE
Azure / SQLite Issue

### ISSUE THREAD

**Issue by firatesmer** [blogifierdotnet/Blogifier#90]
I just cloned a fresh Blogifier from master branch and published it to Azure. I didn't change any line of code or didn't even give a blog name but I got an error while starting the application. Do you guys have any idea how to fix it? Thanks!

this is the website => https://firatesmer.azurewebsites.net/

Screenshot from Azure failures
![image](https://user-images.githubusercontent.com/15785611/34760772-27b7fd60-f5f2-11e7-899d-f80b34acdf29.png)

**Comment by firatesmer** [comment]
I'm sorry SQLite issues are not related to fresh Blogifier but my own blog. Error is still there (SQLite).
I've checked the forums and some people say remove .db file but I already imported my RSS from BlogEngine and If I delete the .db file I will lose hours of work.

**Comment by Nikkinoodl** [comment]
You say that you imported your blog contents from BlogEngine to your new instance via the RSS feed?  At what point did your site stop working?

SqlLite .db files can be copied and pasted like any other file, so you can always make a copy (or several copies) then try deleting the .db file to see if you can get it working.

**Comment by firatesmer** [comment]
Actually, on local my blog is working fine but at host, there are some problems. I first imported my blog content via RSS feed then published.

**Comment by rxtur** [comment]
It is not clear from the screen-shot what actual error is. As Nikkinoodl mentioned, you can troubleshoot by moving and renaming .db files, trying both unchanged and updated. Also, check your log file to see if there is any clues on what actual error is (under /Logs).

**Comment by firatesmer** [comment]
Thanks for replying.

There are two errors in Azure

1. An error occurred using the connection to database 'main' on server 'Data\app.db'.
2. Microsoft.Data.Sqlite.SqliteException / Application startup exception
	Blogifier.Core.Middleware.AppSettingsLoader..ctor Line 26
	
and on my local, there is one error (but it works)

> 2018-01-16 20:19:40.530 +03:00 [Error] Failed executing DbCommand ("3"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
> ""CREATE TABLE \"Categories\" (
>     \"Id\" INTEGER NOT NULL CONSTRAINT \"PK_Categories\" PRIMARY KEY,
>     \"Description\" TEXT NULL,
>     \"ImgSrc\" TEXT NULL,
>     \"LastUpdated\" TEXT NOT NULL,
>     \"ParentId\" INTEGER NOT NULL,
>     \"ProfileId\" INTEGER NOT NULL,
>     \"Rank\" INTEGER NOT NULL,
>     \"Slug\" TEXT NOT NULL,
>     \"Title\" TEXT NOT NULL
> );"
> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "Categories" already exists'.
>    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)

   
later, I removed db and started app on my local, error :

> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "Categories" already exists'.
>    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
> 2018-01-16 20:28:03.620 +03:00 [Error] Failed executing DbCommand ("0"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
> ""CREATE TABLE \"Categories\" (
>     \"Id\" INTEGER NOT NULL CONSTRAINT \"PK_Categories\" PRIMARY KEY,
>     \"Description\" TEXT NULL,
>     \"ImgSrc\" TEXT NULL,
>     \"LastUpdated\" TEXT NOT NULL,
>     \"ParentId\" INTEGER NOT NULL,
>     \"ProfileId\" INTEGER NOT NULL,
>     \"Rank\" INTEGER NOT NULL,
>     \"Slug\" TEXT NOT NULL,
>     \"Title\" TEXT NOT NULL
> );"
> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "Categories" already exists'.
>    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
>    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
> 2018-01-16 20:28:10.862 +03:00 [Error] Error processing embedded resource (.embedded.blog.standard.js.popper.min.js.map) : The given key was not present in the dictionary.

**Comment by rxtur** [comment]
The "table exists" error can be safely ignored, it is thrown by initialization which [can be turned off](https://github.com/blogifierdotnet/Blogifier/wiki/Database#initialize-database).

**Comment by firatesmer** [comment]
Well, your solution fixed my problem but only local. Still fails at Azure. Same error

Is there anything do I have to set up for azure hosting? Any specific option like "choose .NET Core 2.0" or something because I'm out of idea

> Microsoft.Data.Sqlite.SqliteException - An error occurred using the connection to database 'main' on server 'Data\app.db'.
> Microsoft.Data.Sqlite.SqliteException:
>    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC (Microsoft.Data.Sqlite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at Microsoft.Data.Sqlite.SqliteConnection.Open (Microsoft.Data.Sqlite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open (Microsoft.EntityFrameworkCore.Relational, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    
> Blogifier.Core.Middleware.AppSettingsLoader..ctor Line 26
> 
> Microsoft.Data.Sqlite.SqliteException - An error occurred using the connection to database 'main' on server 'Data\app.db'.
> Microsoft.Data.Sqlite.SqliteException:
>    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC (Microsoft.Data.Sqlite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at Microsoft.Data.Sqlite.SqliteConnection.Open (Microsoft.Data.Sqlite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open (Microsoft.EntityFrameworkCore.Relational, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)

Next thing I will try, set InitializeDatabase:false + remove/rename .db file then publish to Azure.

**Comment by Nikkinoodl** [comment]
I don't run on Azure and I've only just switched from Sql Server to Sqlite, but I've met similar problems every time I go through a major upgrade to my website. Here are some things you could try, if you haven't already done so:

1. If you have a working .db on your local machine, try copying the file manually to Azure. Then you know you have a working database instance there. Make sure it's called app.db (personally, I would stick it in App_Data to lessen the risk of overwriting it during publishing—as you know, you can disable publishing to App_Data in Visual Studio).

2. Check the read/write permissions on the file. The application pool that your app runs in needs to have modify, write and read permissions.

3. Double check the connection string in appsettings.json.  Make sure the preceding line has a comma at the end. The connection string should read something like this:

    "Main": "Data Source=Data\\app.db",

4. Finally, try elevating the identity of the application pool from ApplicationPoolIdentity to LocalSystem or an equivalent.

**Comment by firatesmer** [comment]
First step and boom! Found the problem. The problem is I never cheched if there is a db file after publish and no. I just found that I should copy it. Thanks for helping me guys. Problem is fixed.
