### ISSUE TITLE
Cannot find compilation library location for package 'Microsoft.Win32.Registry' resurfaced in asp.net core 2.0 using docker in debug mode

### ISSUE THREAD

**Issue by evilroxx** [blogifierdotnet/Blogifier#92]
Is this issue [Cannot find compilation library location for package 'Microsoft.Win32.Registry'](https://github.com/blogifierdotnet/Blogifier/issues/77) resolved in all scenarios? I'm still seeing the same error when I try to run OOTB MVC netcore2.0app + NET471 in debug mode using Visual Studio 2017 15.5.5 in docker-toolbox linux vm (17.x.x ce). The release mode however works fine. If I reopen a new solution using asp.net core 1.1 using NET 462/471 it works fine. Can someone please share any information they have on how to fix this issue permanently?

**Comment by mdileep** [comment]
I facing the exact issue in DEbug Mode, Release is working without any issues.

**Comment by hunyhabib** [comment]
I still have the same using .net core 2.0 and Docker toolbox on Windows Home using linux image :
 <PropertyGroup>
    netcoreapp2.0
    MvcRazorExcludeRefAssembliesFromPublish : false
    MvcRazorCompileOnPublish : false
  </PropertyGroup>

I added those but still not working. Isn't issue already got resolved and checked in ?
kindly advice.

**Comment by rxtur** [comment]
Moved to 2.1 with lots of code changes, probably not relevant any more.
