### ISSUE TITLE
Can't deploy to Azure

### ISSUE THREAD

**Issue by curia-damiano** [blogifierdotnet/Blogifier#95]
Hi,
the web project can't be deployed to an Azure app service, even if a Windows machine. You get an exception that it can't find the Microsoft.Win32.Registry assembly.
It's because of this issue: https://github.com/dotnet/core-setup/issues/2113 
As suggested in the above issue itself, I have resolved it adding this to the web project file:
<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
Regards, Damiano

**Comment by bchurchill** [comment]
Can confirm.  It looks like the bug report's markup got messed up, this is the line that needs to be added to Blogifier.Web/Blogifier.Web.csproj:

`<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>`
