### ISSUE TITLE
Feedback on publish

### ISSUE THREAD

**Issue by Gaetan-dc** [blogifierdotnet/Blogifier#98]
I was looking for a blog engine in .NET and I stumbled upon Blogifier. I like it a lot but it's not complete enough yet for me to use, so I fall back to BlogEngine.NET. 
However, I have some feedback to offer from my exploration of the project, especially on the publishing process. I haven't really worked with .NET Core before, so some may be due to that.

- The "Data" folder isn't published. It makes the website crash if you use the default SQL Lite because it can't create the database. It would be nice to include it, or to create the path when initializing the  database.
- The "InitializeDatabase" parameter is a bit awkward to use, fortunately it is well documented. In one of my projects I had a similar issue that I fixed this way : the release configuration has this parameter set to true. When the website starts, if true I initialize the database, then I set it to false right after. It was in regular .NET, not Core, so editing the appsettings is easier, from what I can see in Core it's not so trivial to do.
- I had to add `<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>` in the csproj, otherwise the reference dlls wouldn't get copied and the website wouldn't run.
- The widgets don't seem to be available after publish. I haven't had time to look into that one

Not related to publish, but I had some trouble about understanding that the Themes page in the administration is not supposed to work yet. It would be useful that it is made more explicit when that happens, either in comments, by throwing NotImplementedException, etc.

Thanks !

**Comment by rxtur** [comment]
Thanks Gaetan, appreciate your feedback.

**Comment by mawarnes** [comment]
I had a very similar experience, once I updated it to 2.1 everything started working, but it has taken a while. I can successfully deply to azure web app now, which was my goal. Great repo, thank you very much. I added a pull request in case it is helpful here, blogifierdotnet/Blogifier/pull/105
